/*********************
 *      INCLUDES
 *********************/

#include "gui_comm.h"
#include "gui_data_comm.h"
#include "gui_language_comm.h"

/*123456789qwertyuiopasdfghjkl;zzxcvbnm,.*/
const char* language_table_receiver[] = {
	"Receiver",
	"接收方",
	"接收方",
	"Récepteur",
	"Receptor",
	"المستلم",
	"受取人",
	"Получатель",
	"수령자",
	"Recebedor",
	"Recebedor",
	"Destinatario",
	"Empfänger",
	"प्राप्तकर्ता",
	"Хүлээн авагч",
	"ผู้รับเงิน",
	"Одержувач",
	"Người nhận",
	"Penerima",
	"Tagatanggap ng bayad",
	"প্রাপক"
};

const char* language_table_sender[] = {
	"Sender",
	"发送方",
	"发送方",
	"Expéditeur",
	"Emisor",
	"المرسل",
	"送信者",
	"Отправитель",
	"발신자",
	"Remetente",
	"Remetente",
	"Remitente",
	"Absender",
	"प्रेषक",
	"Илгээх хүн",
	"ผู้ส่ง",
	"Відправник",
	"Người gửi",
	"Pengirim",
	"Nagpadala ng bayad",
	"প্রেরক"
};


const char* language_table_format[] = {
	"Format",
	"格式",
	"格式",
	"Format",
	"Formato",
	"تنسيق",
	"フォーマット",
	"Формат",
	"형식",
	"Formato",
	"Formato",
	"Formato",
	"Format",
	"फॉर्मेट",
	"Формат",
	"รูปแบบ",
	"Формат",
	"Định dạng",
	"Format",
	"I-format",
	"ফরম্যাট"
};

const char* language_table_message_amount[] = {
	"Total Amount",
	"总金额",
	"總金額",
	"Montant total",
	"Cantidad total",
	"المبلغ الإجمالي",
	"総額",
	"Общая сумма",
	"총액",
	"Valor total",
	"Valor total",
	"Importo totale",
	"Gesamtbetrag",
	"कुल राशि",
	"Нийт дүн",
	"จำนวนรวม",
	"Загальна сума",
	"Tổng số tiền",
	"Jumlah total",
	"Kabuuang halaga",
	"মোট পরিমাণ"
};

const char* language_table_wallet_ready[] = {
	"Wallet is Ready",
	"钱包已准备好",
	"錢包已準備好",
	"Le portefeuille est prêt",
	"La billetera está lista",
	"المحفظة جاهزة",
	"ウォレットの準備ができました",
	"Кошелек готов",
	"지갑 준비 완료",
	"A carteira está pronta",
	"A carteira está pronta",
	"Il portafoglio è pronto",
	"Die Brieftasche ist bereit",
	"वॉलेट तैयार है",
	"Гаманец гатовы",
	"กระเป๋าเงินพร้อม",
	"Гаманець готовий",
	"Ví sẵn sàng",
	"Dompet siap",
	"Handa na ang Wallet",
	"ওয়ালেট প্রস্তুত"
};

const char* language_table_warning_reset_device[] = {
	"This action will erase all data and cannot be undone. Are you sure you want to proceed?",
	"此操作将清除所有数据，无法撤消。您确定要继续吗？",
	"此操作將刪除所有數據，無法恢復。您確定要繼續嗎？",
	"Cette action effacera toutes les données et ne peut pas être annulée. Vous êtes sûr de vouloir continuer ?",
	"Esta acción borrará todos los datos y no se puede deshacer. ¿Está seguro de que desea continuar?",
	"ستؤدي هذه العملية إلى مسح جميع البيانات ولا يمكن التراجع عنها. هل أنت متأكد أنك تريد المتابعة؟",
	"この操作はすべてのデータを消去し、元に戻すことはできません。本当に続行しますか？",
	"Это действие стерет все данные и его нельзя будет отменить. Вы уверены, что хотите продолжить?",
	"이 작업은 모든 데이터를 지우고 되돌릴 수 없습니다. 계속 진행하시겠습니까?",
	"Esta ação irá apagar todos os dados e não pode ser desfeita. Você tem certeza de que deseja continuar?",
	"Esta acción borrará todos los datos y no se puede deshacer. ¿Está seguro de que desea continuar?",
	"Questa azione eliminerà tutti i dati e non potrà essere annullata. Sei sicuro di voler procedere?",
	"Diese Aktion löscht alle Daten und kann nicht rückgängig gemacht werden. Sind Sie sicher, dass Sie fortfahren möchten?",
	"यह क्रिया सभी डेटा को मिटा देगी और पूर्ववत नहीं की जा सकेगी। क्या आप निश्चित रूप से आगे बढ़ना चाहते हैं?",
	"Эта операция удалит все данные и не может быть отменена. Вы уверены, что хотите продолжить?",
	"การดำเนินการนี้จะลบข้อมูลทั้งหมดและไม่สามารถยกเลิกได้ คุณแน่ใจหรือไม่ว่าต้องการดำเนินการต่อ?",
	"Ця дія знищить всі дані і не може бути скасована. Ви впевненні, що хочете продовжити?",
	"Hành động này sẽ xóa tất cả dữ liệu và không thể hoàn tác. Bạn có chắc chắn muốn tiếp tục không?",
	"Tindakan ini akan menghapus semua data dan tidak dapat diurungkan. Apakah Anda yakin ingin melanjutkan?",
	"Ang aksyong ito ay magbubura ng lahat ng data at hindi maibabalik. Sigurado kang nais magpatuloy?",
	"এই পদক্ষেপটি সমস্ত তথ্য মুছে ফেলবে এবং পূর্বাবস্থায় ফিরিয়ে আনা যাবে না। আপনি কি নিশ্চিতভাবে অগ্রসর হতে চান?"
};

const char* language_table_restore_funds[] = {
	"You can still restore your funds from recovery phrase backup.",
	"您仍然可以从恢复短语备份中恢复您的资金。",
	"您仍然可以從恢復短語備份中恢復您的資金。",
	"Vous pouvez toujours restaurer vos fonds à partir de la sauvegarde de la phrase de récupération.",
	"Aún puedes restaurar tus fondos desde la copia de seguridad de la frase de recuperación.",
	"يمكنك استعادة أموالك من نسخة احتياطية لعبارة الاسترداد.",
	"リカバリフレーズのバックアップから資金を復元できます。",
	"Вы все еще можете восстановить свои средства из резервной копии фразы восстановления.",
	"자금은 복구 구문의 백업에서 여전히 복원할 수 있습니다.",
	"Você ainda pode restaurar seus fundos a partir do backup da frase de recuperação.",
	"Você ainda pode restaurar seus fundos a partir do backup da frase de recuperação.",
	"Puoi ancora ripristinare i tuoi fondi dal backup della frase di recupero.",
	"Sie können Ihre Gelder weiterhin aus der Sicherung der Wiederherstellungsphrase wiederherstellen.",
	"आप अभी भी वसूली वाक्यांश बैकअप से अपने पैसे पुनर्स्थापित कर सकते हैं।",
	"Таамагын харах нь өөрийн хөрөнгийг сэргээж чадна.",
	"คุณยังสามารถกู้คืนเงินของคุณจากการสำรองข้อมูลวลีการกู้คืนได้。",
	"Ви все ще можете відновити свої кошти з резервної копії відновлювальної фрази.",
	"Bạn vẫn có thể phục hồi số tiền của mình từ bản sao lưu cụm từ khôi phục.",
	"Anda masih dapat memulihkan dana Anda dari cadangan frasa pemulihan.",
	"Maaari mo pa ring ibalik ang iyong mga pondo mula sa backup ng recovery phrase.",
	"আপনি এখনও পুনরুদ্ধার বাক্যের ব্যাকআপ থেকে আপনার তহবিল পুনরুদ্ধার করতে পারেন।"
};

const char* language_table_cancel[] = {
	"Cancel",
	"取消",
	"取消",
	"Annuler",
	"Cancelar",
	"إلغاء",
	"キャンセル",
	"Отмена",
	"취소",
	"Cancelar",
	"Cancelar",
	"Annullare",
	"Stornieren",
	"रद्द करें",
	"Цуцлах",
	"ยกเลิก",
	"Скасувати",
	"Hủy bỏ",
	"Batalkan",
	"I-cancel",
	"বাতিল করুন"
};

const char* language_table_screen_never_turn_off[] = {
	"The screen will never turn off.",
	"屏幕将永远不会关闭。",
	"螢幕將永遠不會關閉。",
	"L'écran ne s'éteindra jamais.",
	"La pantalla nunca se apagará.",
	"لن يتم إيقاف تشغيل الشاشة أبدًا.",
	"画面は決して消えません。",
	"Экран никогда не выключится.",
	"화면은 절대 꺼지지 않습니다.",
	"A tela nunca desligará.",
	"A tela nunca desligará.",
	"Lo schermo non si spegnerà mai.",
	"Der Bildschirm wird niemals ausgeschaltet.",
	"स्क्रीन कभी बंद नहीं होगी।",
	"Экран нь хэзээ ч унтрахгүй.",
	"หน้าจอจะไม่ปิดตลอดไป。",
	"Екран ніколи не вимкнеться.",
	"Màn hình sẽ không bao giờ tắt.",
	"Layar tidak akan pernah mati.",
	"Hindi kailanman papatay ang screen.",
	"এই স্ক্রীন কখনও বন্ধ হবে না।"
};

const char* language_table_erase_this_device[] = {
	"Erase This Device",
	"擦除此设备",
	"刪除此裝置",
	"Effacer cet appareil",
	"Borrar este dispositivo",
	"مسح هذا الجهاز",
	"このデバイスを消去",
	"Стереть это устройство",
	"이 장치를 지우기",
	"Apagar este dispositivo",
	"Apagar este dispositivo",
	"Cancellare questo dispositivo",
	"Gerät löschen",
	"इस डिवाइस को मिटाएँ",
	"Устгаг зөөврийн төхөөрөмж",
	"ลบอุปกรณ์นี้",
	"Стерти цей пристрій",
	"Xóa thiết bị này",
	"Hapus perangkat ini",
	"Ibas na ito",
	"এই ডিভাইসটি মুছে দিন"
};

const char* language_table_enter_pin[] = {
	"Enter PIN",
	"输入PIN码",
	"輸入PIN碼",
	"Saisir le code PIN",
	"Introducir PIN",
	"إدخال رمز PIN",
	"PINを入力してください",
	"Введите PIN-код",
	"PIN 입력",
	"Inserir PIN",
	"Inserir PIN",
	"Inserisci il PIN",
	"PIN eingeben",
	"पिन दर्ज करें",
	"PIN код оруулна уу",
	"ป้อนรหัส PIN",
	"Введіть PIN",
	"Nhập mã PIN",
	"Masukkan PIN",
	"Ipasok ang PIN",
	"PIN প্রবেশ করুন",
};

const char* language_table_wrong_pin[] = {
	"Wrong PIN",
	"错误的PIN码",
	"錯誤的PIN碼",
	"PIN incorrect",
	"PIN incorrecto",
	"رمز PIN غير صحيح",
	"間違ったPIN",
	"Неправильный PIN",
	"잘못된 PIN",
	"PIN incorrecto",
	"PIN incorrecto",
	"PIN errato",
	"PIN falsch",
	"गलत PIN",
	"Неправильный PIN",
	"Mã PIN không đúng",
	"PIN salah",
	"Mali ang PIN",
	"ভুল PIN",
};

const char* language_table_entered_incorrect[] = {
	"The PIN you entered is incorrect",
	"您输入的PIN码不正确",
	"您輸入的PIN碼不正確",
	"Le PIN que vous avez saisi est incorrect",
	"El PIN que ingresaste es incorrecto",
	"الرقم السري الذي أدخلته غير صحيح",
	"入力したPINが正しくありません",
	"Введённый вами PIN - код неверен",
	"입력한 PIN이 올바르지 않습니다",
	"O PIN que você inseriu está incorreto",
	"O PIN que você inseriu está incorreto",
	"Il PIN che hai inserito non è corretto",
	"Der eingegebene PIN ist falsch",
	"जो PIN आपने दर्ज किया है वह गलत है",
	"Та PIN, который вы ввели, неверен",
	"PIN ที่คุณป้อนไม่ถูกต้อง",
	"Введено неверное PIN",
	"Mã PIN bạn nhập không đúng",
	"PIN yang Anda masukkan salah",
	"Ang PIN na ipinasok mo ay mali",
	"আপনি যে PIN প্রবেশ করেছেন তা ভুল",
};

const char* language_table_close[] = {
	"Close",
	"关闭",
	"關閉",
	"Fermer",
	"Cerrar",
	"إغلاق",
	"閉じる",
	"Закрыть",
	"닫기",
	"Fechar",
	"Fechar",
	"Chiudi",
	"Schließen",
	"बंद करें",
	"Хаах",
	"ปิด",
	"Закрити",
	"Đóng",
	"Tutup",
	"Isara",
	"বন্ধ",
};

const char* language_table_enter_new_pin[] = {
	"Enter New PIN",
	"输入新PIN码",
	"輸入新PIN碼",
	"Saisir le nouveau PIN",
	"Ingresar nuevo PIN",
	"أدخل رقم PIN جديد",
	"新しいPINを入力してください",
	"Введите новый PIN - код",
	"새 PIN 입력",
	"Inserir novo PIN",
	"Inserir novo PIN",
	"Inserisci un nuovo PIN",
	"Geben Sie neue PIN ein",
	"नई PIN दर्ज करें",
	"Введите новый PIN - код",
	"ป้อน PIN ใหม",
	"Введіть новий PIN-код",
	"Nhập PIN mới",
	"Masukkan PIN baru",
	"Ipasok ang bagong PIN",
	"নতুন পিন প্রবেশ করুন",
};

const char* language_table_confirm_pin[] = {
	"Confirm PIN",
	"确认PIN码",
	"確認PIN碼",
	"Confirmer le PIN",
	"Confirmar PIN",
	"تأكيد الرقم السري",
	"PINを確認する",
	"Подтвердите PIN - код",
	"PIN 확인",
	"Confirmar PIN",
	"Confirmar PIN",
	"Conferma PIN",
	"Bestätigen Sie den PIN",
	"पिन की पुष्टि करें",
	"Підтвердьте PIN - код",
	"ยืนยัน PIN",
	"Підтвердіть PIN - код",
	"Xác nhận PIN",
	"Konfirmasi PIN",
	"Kumpirmahin ang PIN",
	"পিন নিশ্চিত করুন",
};

const char* language_table_swipe_to_show_app[] = {
	"Swipe up to show apps",
	"向上滑动显示应用",
	"向上滑動顯示應用程式",
	"Faire glisser vers le haut pour afficher les applications",
	"Desliza hacia arriba para mostrar las aplicaciones",
	"اسحب لأعلى لعرض التطبيقات",
	"アプリを表示するにはスワイプアップ",
	"Проведите вверх, чтобы показать приложения",
	"앱을 표시하려면 위로 스와이프",
	"Deslizar para cima para mostrar apps",
	"Il deslizamento verso l'alto per mostrare le app",
	"Wischen Sie nach oben, um Apps anzuzeigen",
	"Свайпните вверх, чтобы показать приложения",
	"Свайпайте вверх, чтобы показать приложения",
	"เลื่อนขึ้นเพื่อแสดงแอป",
	"Проведіть вгору, щоб показати додатки",
	"Vuốt lên để hiển thị ứng dụng",
	"Geser ke atas untuk menampilkan aplikasi",
	"Mag-swipe pataas upang ipakita ang mga app",
	"স্লাইড আপ করে অ্যাপস প্রদর্শন করুন",
};

const char* language_table_quick_start[] = {
	"Quick Start",
	"快速开始",
	"快速開始",
	"Démarrer rapidement",
	"Inicio rápido",
	"بدء سريع",
	"クイックスタート",
	"Быстрый старт",
	"빠른 시작",
	"Início rápido",
	"Início rápido",
	"Avvio veloce",
	"Schneller Start",
	"त्वरित प्रारंभ",
	"Түргэн эхлэл",
	"เริ่มต้นอย่างรวดเร็ว",
	"Швидкий старт",
	"Khởi động nhanh",
	"Mulai cepat",
	"Mabilis na pagsimula",
	"দ্রুত শুরু",
};

const char* language_table_create_wallet_or_restore[] = {
	"Create a new wallet, or restore a previously used wallet from recovery phrase backup.",
	"创建新钱包，或从恢复短语备份恢复以前使用的钱包。",
	"創建一個新錢包，或從恢復短語備份恢復以前使用的錢包。",
	"Créez un nouveau portefeuille ou restaurez un portefeuille précédemment utilisé à partir d'une sauvegarde de phrase de récupération.",
	"Crea una nueva billetera o restaura una billetera previamente utilizada desde una copia de seguridad de la frase de recuperación.",
	"أنشئ محفظة جديدة، أو استعد محفظة استخدمتها سابقًا من نسخة احتياطية لعبارة الاسترداد.",
	"新しいウォレットを作成するか、リカバリーフレーズバックアップから以前使用していたウォレットを復元します。",
	"Создайте новый кошелек или восстановите ранее использованный кошелек из резервной копии фразы восстановления.",
	"Crie uma nova carteira ou restaure uma carteira previamente usada a partir de um backup da frase de recuperação.",
	"Crea un nuovo portafoglio o ripristina un portafoglio precedentemente utilizzato da un backup della frase di recupero.",
	"Erstellen Sie ein neues Wallet oder stellen Sie ein zuvor verwendetes Wallet aus einem Wiederherstellungssatz-Backup wieder her.",
	"नया वॉलेट बनाएं, या पुनर्प्राप्ति वाक्यांश बैकअप से पहले उपयोग किए गए वॉलेट को पुनर्स्थापित करें।",
	"Шинэ түрийвч үүсгэ, эсвэл сэргээх үгний нөөцөөс өмнө ашигласан түрийвчийг сэргээ.",
	"สร้างกระเป๋าเงินใหม่ หรือกู้คืนกระเป๋าเงินที่เคยใช้จากการสำรองประโยคการกู้คืน",
	"Створіть новий гаманець або відновіть раніше використаний гаманець з резервної копії фрази відновлення.",
	"Tạo ví mới hoặc khôi phục ví đã sử dụng trước đó từ bản sao lưu cụm từ phục hồi.",
	"Buat dompet baru atau pulihkan dompet yang telah digunakan sebelumnya dari cadangan frasa pemulihan.",
	"Lumikha ng bagong wallet, o ibalik ang isang wallet na dati nang ginamit mula sa backup ng recovery phrase.",
	"নতুন ওয়ালেট তৈরি করুন, অথবা পুনরুদ্ধার বাক্যাংশ ব্যাকআপ থেকে পূর্বে ব্যবহৃত ওয়ালেট পুনরুদ্ধার করুন।",
};

const char* language_table_create_wallet[] = {
	"Create Wallet",
	"创建钱包",
	"創建錢包",
	"Créer un portefeuille",
	"Crear billetera",
	"أنشئ محفظة",
	"ウォレットを作成する",
	"Создать кошелек",
	"지갑 만들기",
	"Criar Carteira",
	"Criar Carteira",
	"Crea Wallet",
	"Wallet erstellen",
	"वॉलेट बनाएं",
	"Багц хэтэвч үүсгэх",
	"สร้างกระเป๋า",
	"Створити гаманець",
	"Tạo ví",
	"Buat Dompet",
	"Lumikha ng Wallet",
	"ক্রিয়েট ওয়ালেট",
};

const char* language_table_import_wallet[] = {
	"Import Wallet",
	"导入钱包",
	"匯入錢包",
	"Importer un portefeuille",
	"Importar billetera",
	"استيراد المحفظة",
	"ウォレットをインポートする",
	"Импортировать кошелек",
	"지갑 가져오기",
	"Importar Carteira",
	"Importar Carteira",
	"Importa Wallet",
	"Wallet importieren",
	"वॉलेट आयात करें",
	"Хэтэвч оруулах",
	"นำเข้ากระเป๋า",
	"Імпортувати гаманець",
	"Nhập ví",
	"Impor Dompet",
	"I - import ang Wallet",
	"ইম্পোর্ট ওয়ালেট",
};

const char* language_table_ready_to_check[] = {
	"Ready to Check!",
	"准备检查!",
	"準備檢查!",
	"Prêt à vérifier!",
	"Listo para comprobar!",
	"جاهز للتحقق",
	"チェックする準備ができました!",
	"Готово к проверке",
	"준비 완료!",
	"Pronto para Checar",
	"Pronto para Checar",
	"Pronto per il controllo",
	"Bereit zur Überprüfung",
	"चेक करने के लिए तैयार",
	"Шалгалт хийхэд бэлэн",
	"Готово до перевірки",
	"Sẵn sàng kiểm tra",
	"Siap untuk Memeriksa",
	"Handa nang Suriin",
	"যাচাই করার জন্য প্রস্তুত",
};
const char* language_table_select_number_of_words[] = {
	"Select the number of words.",
	"选择单词数量。",
	"選擇單詞數量。",
	"Sélectionner le nombre de mots.",
	"Seleccione el número de palabras.",
	"اختر عدد الكلمات",
	"単語の数を選択する.",
	"Выберите количество слов.",
	"단어 수 선택",
	"Selecione o número de palavras",
	"Selecione o número de palavras",
	"Seleziona il numero di parole",
	"Wählen Sie die Anzahl der Wörter",
	"शब्दों की संख्या चुनें",
	"Сайтад тоо сонгох",
	"เลือกจำนวนคำ",
	"Виберіть кількість слів",
	"Chọn số từ",
	"Pilih jumlah kata",
	"Piliin ang bilang ng mga salita",
	"শব্দের সংখ্যা নির্বাচন করুন",
};

const char* language_table_words[] = {
	"Words",
	"单词",
	"單詞",
	"Mots",
	"Palabras",
	"كلمات",
	"単語",
	"Слова",
	"단어",
	"Palavras",
	"Palavras",
	"Parole",
	"Wörter",
	"शब्द",
	"Үг",
	"คำ",
	"слів",
	"từ",
	"kata",
	"mga salita",
	"শব্দ",
};

const char* language_table_recovery_phrase[] = {
	"Recovery Phrase",
	"恢复短语",
	"恢復短語",
	"Phrase de récupération",
	"Frase de recuperación",
	"العبارة الاسترداد",
	"リカバリーフレーズ",
	"Фраза восстановления",
	"복구 문구",
	"Frase de recuperação",
	"Frase de recuperação",
	"Frase di recupero",
	"Wiederherstellungsphrase",
	"पुनर्प्राप्ति वाक्यांश",
	"Сэргээх хэллэг",
	"วลีการกู้คืน",
	"Фраза відновлення",
	"Cụm từ khôi phục",
	"Frasa Pemulihan",
	"Parirala sa Pagbawi",
	"পুনরুদ্ধারের শব্দগুচ্ছ",
};

const char* language_table_write_down_following[] = {
	"Write down the following %d Words in orders.",
	"按顺序写下以下%d个单词",
	"按順序寫下以下%d個單詞",
	"Notez les %d mots suivants dans l'ordre",
	"Escriba las siguientes %d palabras en orden",
	"اكتب الكلمات الاثنتي عشرة التالية بالترتيب",
	"以下の12個の単語を順番に書いてください",
	"Запишите следующие %d слов в порядке",
	"다음 12개의 단어를 순서대로 적으십시오",
	"Escreva as seguintes %d palavras na ordem",
	"Escreva as seguintes %d palavras na ordem",
	"Scrivi le seguenti %d parole in ordine",
	"Notieren Sie die folgenden %d Wörter in der Reihenfolge",
	"निम्नलिखित %d शब्दों को क्रम में लिखें",
	"Дараалалд %d үгийг бичнэ үү",
	"เขียนคำ %d คำต่อไปนี้ตามลำดับ",
	"Напишіть наступні %d слів у порядку",
	"Ghi lại %d từ sau theo thứ tự",
	"Tuliskan %d kata berikut dalam urutan",
	"Isulat ang %d salita sa pagkakasunod-sunod",
	"নিম্নলিখিত%d টি শব্দ ক্রমানুসারে লিখুন"
};


const char* language_table_continue[] = {
	"Continue",
	"继续",
	"繼續",
	"Continuer",
	"Continuar",
	"استمر",
	"続行",
	"Продолжить",
	"계속",
	"Continuar",
	"Continuar",
	"Continuare",
	"Fortfahren",
	"जारी रखें",
	"Үргэлжлүүлэх",
	"ดำเนินการต่อ",
	"Продовжити",
	"Tiếp tục",
	"Lanjutkan",
	"Magpatuloy",
	"চালিয়ে যান"
};

const char* language_table_almost_done[] = {
	"Almost Done!",
	"快完成了！",
	"快完成了！",
	"Presque terminé !",
	"¡Casi listo!",
	"انتهيت تقريبًا!",
	"ほぼ完了です！",
	"Почти готово!",
	"거의 다 되었습니다!",
	"Quase pronto!",
	"Quase pronto!",
	"Quasi fatto!",
	"Fast fertig!",
	"लगभग हो ही गया!",
	"Бараг л дууслаа!",
	"เกือบเสร็จแล้ว!",
	"Майже готово!",
	"Gần xong rồi!",
	"Hampir Selesai!",
	"Malapit na!",
	"প্রায় শেষ হয়ে গেছে!"
};


const char* language_table_follow_the_guide[] = {
	"Next, Following the guide and check words one by one, based on your recovery phrase backup.",
	"接下来，按照指南逐一检查单词，基于您的恢复短语备份。",
	"接下來，按照指南逐一檢查單詞，基於您的恢復短語備份。",
	"Ensuite, suivez le guide et vérifiez les mots un par un, en vous basant sur votre phrase de récupération.",
	"A continuación, siga la guía y revise las palabras una por una, basado en su frase de recuperación.",
	"بعد ذلك، اتبع الدليل وراجع الكلمات واحدة تلو الأخرى، بناءً على عبارة الاسترداد الخاصة بك.",
	"次に、ガイドに従い、リカバリーフレーズバックアップに基づいて、単語を一つずつ確認します。",
	"Далее следуйте руководству и проверяйте слова одно за другим, основываясь на вашей фразе для восстановления.",
	"다음으로 가이드를 따라 복구 구문 백업을 기준으로 단어를 하나씩 확인하세요.",
	"Em seguida, siga o guia e verifique as palavras uma por uma, com base na sua frase de recuperação.",
	"Em seguida, siga o guia e verifique as palavras uma a uma, com base na sua frase de recuperação.",
	"Successivamente, segui la guida e controlla le parole una per una, basandoti sulla tua frase di recupero.",
	"Danach folgen Sie der Anleitung und überprüfen Sie die Wörter einzeln, basierend auf Ihrem Wiederherstellungssatz.",
	"इसके बाद, गाइड का पालन करें और अपनी रिकवरी वाक्यांश बैकअप के आधार पर शब्दों की एक-एक करके जांच करें。",
	"Дальше следуйте руководству и проверяйте слова по очереди, основываясь на вашей фразе для восстановления.",
	"ต่อไป ให้ปฏิบัติตามคู่มือและตรวจสอบคำทีละคำ โดยอิงจากคำสำรองการกู้คืนของคุณ",
	"Далі слідуйте інструкціям та перевіряйте слова одне за одним, спираючись на вашу фразу відновлення.",
	"Tiếp theo, hãy theo hướng dẫn và kiểm tra từng từ một, dựa trên cụm từ khôi phục của bạn.",
	"Selanjutnya, ikuti panduan dan periksa kata satu per satu, berdasarkan frasa pemulihan Anda.",
	"Susunod, sundin ang gabay at suriin ang mga salita isa-isa, batay sa iyong recovery phrase backup.",
	"পরবর্তী, গাইড অনুসরণ করুন এবং আপনার পুনরুদ্ধার বাক্যাংশের ব্যাকআপের ভিত্তিতে একে একে শব্দগুলি পরীক্ষা করুন。"
};
const char* language_table_back[] = {
	"Back",
	"返回",
	"返回",
	"Retour",
	"Regresar",
	"العودة",
	"戻る",
	"Назад",
	"뒤로",
	"Voltar",
	"Voltar",
	"Indietro",
	"Zurück",
	"वापस",
	"Буцаах",
	"ย้อนกลับ",
	"Назад",
	"Quay lại",
	"Kembali",
	"Bumalik",
	"ফিরে যান"
};
const char* language_table_verification_phrase[] = {
	"Verification Phrase",
	"验证短语",
	"驗證短語",
	"Phrase de vérification",
	"Frase de verificación",
	"عبارة التحقق",
	"検証フレーズ",
	"Фраза проверки",
	"확인 문구",
	"Frase de verificação",
	"Frase de verificação",
	"Frase di verifica",
	"Überprüfungsphrase",
	"सत्यापन वाक्यांश",
	"Баталгаажуулах хэллэг",
	"วลีการตรวจสอบ",
	"Фраза перевірки",
	"Cụm từ xác minh",
	"Frasa verifikasi",
	"Pahayag ng Pag-verify",
	"যাচাইকরণ বাক্যাংশ"
};
const char* language_table_verification_word[] = {
	"Verification Word",
	"验证词",
	"驗證詞",
	"Mot de vérification",
	"Palabra de verificación",
	"كلمة التحقق",
	"検証語",
	"Слово проверки",
	"인증 단어",
	"Palavra de verificação",
	"Palavra de verificação",
	"Parola di verifica",
	"Überprüfungswort",
	"सत्यापन शब्द",
	"Баталгаажуулалтын үг",
	"คำยืนยัน",
	"Слово підтвердження",
	"Từ xác minh",
	"Kata Verifikasi",
	"Salitang Berifikasi",
	"যাচাইকরণ শব্দ"
};
const char* language_table_incorrect_word[] = {
	"Incorrect Word",
	"错误词",
	"錯誤詞",
	"Mot incorrect",
	"Palabra incorrecta",
	"الكلمة غير الصحيحة",
	"誤った語",
	"Неправильное слово",
	"잘못된 단어",
	"Palavra incorreta",
	"Palavra incorreta",
	"Parola errata",
	"Falsches Wort",
	"गलत शब्द",
	"Буруу үг",
	"คำผิด",
	"Неправильне слово",
	"Từ sai",
	"Kata Salah",
	"Mali na Salita",
	"ভুল শব্দ"
};
const char* language_table_wrong_word_check_again[] = {
	"This is a wrong word, check your backup and try again.",
	"这是一个错误的词，请检查您的备份并重试。",
	"這是錯誤的詞，請檢查備份後重試。",
	"C'est un mot incorrect, vérifiez votre sauvegarde et réessayez.",
	"Esta es una palabra incorrecta, verifique su copia de seguridad e intente de nuevo.",
	"هذه كلمة خاطئة، تحقق من النسخة الاحتياطية وحاول مرة أخرى.",
	"これは間違った単語です。バックアップを確認して再試行してください。",
	"Это неправильное слово, проверьте резервную копию и попробуйте снова.",
	"잘못된 단어입니다. 백업을 확인하고 다시 시도해 주세요.",
	"Esta é uma palavra incorreta, verifique seu backup e tente novamente.",
	"Esta é uma palavra incorreta, verifique seu backup e tente novamente.",
	"Questa è una parola sbagliata, controlla il tuo backup e riprova.",
	"Dies ist ein falsches Wort, überprüfen Sie Ihr Backup und versuchen Sie es erneut.",
	"यह एक गलत शब्द है, कृपया अपना बैकअप जांचें और पुनः प्रयास करें।",
	"Энэ нь буруу үг бөгөөд, нөөц хуулгаа шалгаж дахин оролдож үзнэ үү.",
	"นี่คือลักษณะผิด ตรวจสอบสำรองข้อมูลของคุณและลองอีกครั้ง",
	"Це неправильне слово, перевірте свою резервну копію та спробуйте ще раз.",
	"Đây là một từ sai, kiểm tra bản sao lưu của bạn và thử lại.",
	"Ini adalah kata yang salah, periksa cadangan Anda dan coba lagi.",
	"Ito ay maling salita, suriin ang iyong backup at subukang muli.",
	"এটা একটি ভুল শব্দ, আপনার ব্যাকআপ চেক করুন এবং আবার চেষ্টা করুন。"
};
const char* language_table_try_again[] = {
	"Try Again",
	"再试一次",
	"再試一次",
	"Réessayez",
	"Inténtelo de nuevo",
	"حاول مرة أخرى",
	"もう一度やってみてください",
	"Попробуйте снова",
	"다시 시도해 보세요",
	"Tente novamente",
	"Tente novamente",
	"Riprovare",
	"Versuchen Sie es erneut",
	"फिर से प्रयास करें",
	"Дахин оролдоно уу",
	"ลองอีกครั้ง",
	"Спробуйте ще раз",
	"Thử lại",
	"Coba lagi",
	"Subukan muli",
	"আরও চেষ্টা করুন"
};
const char* language_table_user_guide[] = {
	"User Guide",
	"用户指南",
	"使用说明",
	"Guide de l'utilisateur",
	"Guía del usuario",
	"دليل المستخدم",
	"ユーザーガイド",
	"Руководство пользователя",
	"사용자 가이드",
	"Guia do Usuário",
	"Guia do Usuário",
	"Guida dell'utente",
	"Benutzerhandbuch",
	"उपयोगकर्ता गाइड",
	"Хэрэглэгчийн гарын авлага",
	"คู่มือผู้ใช้",
	"Посібник користувача",
	"Hướng dẫn người dùng",
	"Panduan Pengguna",
	"Patnubay ng Gumagamit",
	"ব্যবহারকারী গাইড"
};
const char* language_table_kikkim_app_tutorial[] = {
	"LIKKIM App Tutorial",
	"LIKKIM 应用教程",
	"LIKKIM 應用教程",
	"Tutoriel de l'application LIKKIM",
	"Tutorial de la aplicación LIKKIM",
	"برنامج LIKKIM التعليمي",
	"LIKKIM アプリチュートリアル",
	"Учебное пособие по приложению LIKKIM",
	"LIKKIM 앱 튜토리얼",
	"Tutorial do Aplicativo LIKKIM",
	"Tutorial do Aplicativo LIKKIM",
	"Guida all'app LIKKIM",
	"LIKKIM-App-Tutorial",
	"LIKKIM ऐप ट्यूटोरियल",
	"LIKKIM апп сургалт",
	"คู่มือแอป LIKKIM",
	"Підручник по додатку LIKKIM",
	"Hướng dẫn ứng dụng LIKKIM",
	"Tutorial Aplikasi LIKKIM",
	"LIKKIM App Tutorial",
	"LIKKIM অ্যাপ টিউটোরিয়াল"
};
const char* language_table_what_is_recovery_phrase[] = {
	"What is Recovery Phrase?",
	"什么是恢复短语？",
	"什麼是恢復短語？",
	"Qu'est-ce qu'une phrase de récupération ?",
	"¿Qué es una frase de recuperación?",
	"ما هي عبارة الاسترداد؟",
	"リカバリーフレーズとは？",
	"Что такое фраза восстановления?",
	"복구 문구란 무엇입니까?",
	"O que é uma frase de recuperação?",
	"O que é uma frase de recuperação?",
	"Che cos'è una frase di recupero?",
	"Was ist eine Wiederherstellungsphrase?",
	"रिकवरी वाक्यांश क्या है?",
	"Нэр томъёо гэж юу вэ?",
	"ฟразาฟื้นฟูคืออะไร?",
	"Що таке фраза відновлення?",
	"Cụm từ phục hồi là gì?",
	"Apa itu frasa pemulihan?",
	"Ano ang Recovery Phrase?",
	"পুনরুদ্ধার বাক্যাংশ কি?"
};
const char* language_table_recovery_phrase_description[] = {
    "The term 'Recovery Phrase' is commonly used in the context of cryptocurrency wallets to refer to a sequence of words generated by your wallet that gives you access to the funds associated with that wallet. This phrase is sometimes called a 'seed phrase' or 'backup phrase.'",
    "‘恢复短语’这一术语通常在加密货币钱包的上下文中使用，指的是由钱包生成的一系列单词，这些单词可以让你访问与该钱包相关的资金。这个短语有时被称为‘助记词’或‘备份短语’。",
    "'恢復短語'這一術語通常在加密貨幣錢包的上下文中使用，指的是由錢包生成的一系列單詞，這些單詞可以讓你訪問與該錢包相關的資金。 這個短語有時被稱為『助記詞』或『備份短語』。",
    "Le terme 'phrase de récupération' est couramment utilisé dans le contexte des portefeuilles de cryptomonnaie pour désigner une séquence de mots générée par votre portefeuille qui vous donne accès aux fonds associés à ce portefeuille. Cette phrase est parfois appelée 'phrase de seed' ou 'phrase de sauvegarde.'",
    "El término 'frase de recuperación' se usa comúnmente en el contexto de las billeteras de criptomonedas para referirse a una secuencia de palabras generada por su billetera que le da acceso a los fondos asociados con esa billetera. Esta frase a veces se llama 'frase semilla' o 'frase de respaldo.'",
    "تُستخدم عبارة 'عبارة الاسترداد' عادةً في سياق محافظ العملات المشفرة للإشارة إلى سلسلة من الكلمات التي ينشئها محفظتك والتي تمنحك الوصول إلى الأموال المرتبطة بهذه المحفظة. تُسمى هذه العبارة أحيانًا 'عبارة بذور' أو 'عبارة النسخ الاحتياطي.'",
    "「リカバリーフレーズ」という用語は、暗号通貨ウォレットの文脈で一般的に使用されており、そのウォレットによって生成された単語のシーケンスを指し、それに関連する資金にアクセスするためのものです。このフレーズは時々「シードフレーズ」または「バックアップフレーズ」と呼ばれることがあります。",
    "Термин 'фраза восстановления' обычно используется в контексте криптовалютных кошельков для обозначения последовательности слов, сгенерированной вашим кошельком, которая дает вам доступ к средствам, связанным с этим кошельком. Эта фраза иногда называется 'seed-фраза' или 'резервная фраза.'",
    "‘복구 문구’라는 용어는 암호화폐 지갑의 맥락에서 자주 사용되며, 지갑에서 생성된 일련의 단어를 가리키며, 이를 통해 해당 지갑과 연결된 자금에 접근할 수 있습니다. 이 문구는 때때로 '시드 문구' 또는 '백업 문구'라고도 불립니다.",
    "O termo 'frase de recuperação' é comumente usado no contexto de carteiras de criptomoedas para se referir a uma sequência de palavras geradas pela sua carteira que lhe dá acesso aos fundos associados a essa carteira. Esta frase às vezes é chamada de 'frase seed' ou 'frase de backup.'",
    "O termo 'frase de recuperação' é comumente usado no contexto de carteiras de criptomoedas para se referir a uma sequência de palavras geradas pela sua carteira que lhe dá acesso aos fundos associados a essa carteira. Esta frase às vezes é chamada de 'frase seed' ou 'frase de backup.'",
    "Il termine 'frase di recupero' è comunemente usato nel contesto dei portafogli di criptovalute per riferirsi a una sequenza di parole generate dal tuo portafoglio che ti dà accesso ai fondi associati a quel portafoglio. Questa frase è a volte chiamata 'frase seed' o 'frase di backup.'",
    "Der Begriff 'Wiederherstellungsphrase' wird häufig im Zusammenhang mit Kryptowährungs-Wallets verwendet, um eine Folge von Wörtern zu bezeichnen, die von Ihrem Wallet generiert wird und Ihnen Zugang zu den mit diesem Wallet verbundenen Mitteln gibt. Diese Phrase wird manchmal als 'Seed-Phrase' oder 'Backup-Phrase' bezeichnet.",
    "रिकवरी वाक्यांश 'शब्द' का उपयोग आम तौर पर क्रिप्टोक्यूरेंसी वॉलेट के संदर्भ में किया जाता है जो आपके वॉलेट द्वारा उत्पन्न शब्दों की एक श्रृंखला को संदर्भित करता है जो आपको उस वॉलेट से संबंधित फंड तक पहुँचा देता है। इस वाक्यांश को कभी-कभी 'बीज वाक्यांश' या 'बैकअप वाक्यांश' कहा जाता है।",
    "Термин 'нэр томъёо' обычно используется в контексте криптовалютных кошельков для обозначения последовательности слов, сгенерированных вашим кошельком, которая предоставляет доступ к средствам, связанным с этим кошельком. Эта фраза иногда называется 'seed-томъёо' или 'резервный томъёо.'",
    "คำว่า 'วลีฟื้นฟู' จะใช้กันทั่วไปในบริบทของกระเป๋าเงินดิจิทัลเพื่ออ้างอิงถึงลำดับของคำที่สร้างโดยกระเป๋าของคุณซึ่งให้สิทธิ์เข้าถึงเงินที่เชื่อมโยงกับกระเป๋านั้น วลีนี้บางครั้งถูกเรียกว่า 'วลีเมล็ด' หรือ 'วลีสำรอง.'",
    "Термін 'фраза відновлення' часто використовується в контексті криптовалютних гаманців для позначення послідовності слів, згенерованої вашим гаманцем, яка надає вам доступ до коштів, пов'язаних з цим гаманцем. Цю фразу іноді називають 'seed-фразою' або 'резервною фразою.'",
    "Cụm từ 'cụm từ phục hồi' thường được sử dụng trong ngữ cảnh của ví tiền điện tử để chỉ một chuỗi từ được tạo ra bởi ví của bạn, cho phép bạn truy cập vào các quỹ liên quan đến ví đó. Cụm từ này đôi khi được gọi là 'cụm từ hạt giống' hoặc 'cụm từ sao lưu.'",
    "Istilah 'frasa pemulihan' umumnya digunakan dalam konteks dompet kripto untuk merujuk pada sekumpulan kata yang dihasilkan oleh dompet Anda yang memberi Anda akses ke dana yang terkait dengan dompet tersebut. Frasa ini terkadang disebut sebagai 'frasa biji' atau 'frasa cadangan.'",
    "Ang terminong 'Recovery Phrase' ay karaniwang ginagamit sa konteksto ng mga cryptocurrency wallet upang tumukoy sa isang pagkakasunod-sunod ng mga salita na nabuo ng iyong wallet na nagbibigay sa iyo ng access sa mga pondo na nauugnay sa wallet na iyon. Ang parirala ito ay kung minsan ay tinatawag na 'seed phrase' o 'backup phrase.'",
    "‘পুনরুদ্ধার বাক্যাংশ’ সাধারণত ক্রিপ্টোকারেন্সি ওয়ালেটের প্রেক্ষাপটে ব্যবহৃত হয়, আপনার ওয়ালেট দ্বারা তৈরি করা একটি শব্দের সিকোয়েন্সকে নির্দেশ করতে যা আপনাকে সেই ওয়ালেটের সাথে সম্পর্কিত তহবিলে প্রবেশাধিকার দেয়। এই বাক্যাংশটিকে মাঝে মাঝে ‘বীজ বাক্যাংশ’ বা ‘ব্যাকআপ বাক্যাংশ’ বলা হয়।"
};

const char* language_table_welcome_to_likkim[] = {
	"Welcome to LIKKIM, your secure cold wallet solution.",
	"欢迎使用 LIKKIM，您的安全冷钱包解决方案。",
	"歡迎使用 LIKKIM，您的安全冷錢包解決方案。",
	"Bienvenue sur LIKKIM, votre solution de portefeuille froid sécurisé.",
	"Bienvenido a LIKKIM, su solución segura para billeteras frías.",
	"مرحبا بك في LIKKIM، حل محفظتك الباردة الآمنة.",
	"LIKKIM へようこそ、安全なコールドウォレットソリューションです。",
	"Добро пожаловать в LIKKIM, ваше безопасное решение для холодных кошельков.",
	"LIKKIM에 오신 것을 환영합니다, 귀하의 안전한 콜드 월렛 솔루션.",
	"Bem-vindo ao LIKKIM, sua solução segura de carteira fria.",
	"Bem-vindo ao LIKKIM, sua solução segura de carteira fria.",
	"Benvenuto su LIKKIM, la tua soluzione sicura per portafogli freddi.",
	"Willkommen bei LIKKIM, Ihrer sicheren Lösung für Kaltbrieftaschen.",
	"LIKKIM में आपका स्वागत है, आपका सुरक्षित कोल्ड वॉलेट समाधान।",
	"LIKKIM-д тавтай морил, таны аюулгүй хүйтэн түрийвчний шийдэл.",
	"ยินดีต้อนรับสู่ LIKKIM โซลูชันกระเป๋าเงินเย็นที่ปลอดภัยของคุณ",
	"Ласкаво просимо в LIKKIM, ваше безпечне рішення для холодних гаманців.",
	"Chào mừng bạn đến với LIKKIM, giải pháp ví lạnh an toàn của bạn.",
	"Selamat datang di LIKKIM, solusi dompet dingin aman Anda.",
	"Maligayang pagdating sa LIKKIM, ang iyong ligtas na malamig na solusyon sa pitaka.",
	"স্বাগতম LIKKIM এ, আপনার নিরাপদ কোল্ড ওয়ালেট সমাধান।"
};
const char* language_table_recovery_phrase_instruction[] = {
	"The term \"Recovery Phrase\" is commonly used in the context of cryptocurrency wallets to refer to a sequence of words generated by your wallet that gives you access to the funds associated with that wallet. This phrase is sometimes called a \"seed phrase\" or \"backup phrase.\"",
	"“恢复短语”这个术语通常用于加密货币钱包的上下文中，指的是由钱包生成的一系列单词，这些单词可以让您访问与该钱包相关的资金。这个短语有时也叫做“种子短语”或“备份短语”。",
	"“恢復短語”這個術語通常用於加密貨幣錢包的上下文中，指的是由錢包生成的一系列單詞，這些單詞可以讓您訪問與該錢包相關的資金。這個短語有時也叫做“種子短語”或“備份短語”。",
	"Le terme \"phrase de récupération\" est couramment utilisé dans le contexte des portefeuilles de cryptomonnaie pour désigner une séquence de mots générés par votre portefeuille qui vous donne accès aux fonds associés à ce portefeuille. Cette phrase est parfois appelée \"phrase de sauvegarde\" ou \"phrase secrète\".",
	"El término \"frase de recuperación\" se usa comúnmente en el contexto de las billeteras de criptomonedas para referirse a una secuencia de palabras generadas por su billetera que le da acceso a los fondos asociados con esa billetera. Esta frase a veces se llama \"frase semilla\" o \"frase de respaldo\".",
	"مصطلح \"عبارة الاسترداد\" يُستخدم عادةً في سياق محافظ العملات الرقمية للإشارة إلى تسلسل من الكلمات التي يتم إنشاؤها بواسطة محفظتك والتي تمنحك الوصول إلى الأموال المرتبطة بتلك المحفظة. تُسمى هذه العبارة أحيانًا \"عبارة البذور\" أو \"عبارة النسخ الاحتياطي\".",
	"「リカバリーフレーズ」という用語は、暗号通貨ウォレットの文脈で一般的に使用され、ウォレットによって生成された単語のシーケンスを指します。これにより、そのウォレットに関連付けられた資金にアクセスできます。このフレーズは、時々「シードフレーズ」または「バックアップフレーズ」と呼ばれることもあります。",
	"Термин \"фраза восстановления\" обычно используется в контексте криптовалютных кошельков и относится к последовательности слов, сгенерированных вашим кошельком, которые предоставляют доступ к средствам, связанным с этим кошельком. Эта фраза иногда называется \"seed-фразой\" или \"фразой резервного копирования\".",
	"\"복구 문구\"라는 용어는 암호화폐 지갑의 맥락에서 일반적으로 사용되며, 지갑이 생성한 일련의 단어를 나타냅니다. 이 문구를 통해 지갑과 관련된 자금에 접근할 수 있습니다. 이 문구는 때때로 \"시드 문구\" 또는 \"백업 문구\"라고도 합니다.",
	"O termo \"Frase de Recuperação\" é comumente usado no contexto de carteiras de criptomoeda para se referir a uma sequência de palavras geradas pela sua carteira que lhe dá acesso aos fundos associados a essa carteira. Esta frase às vezes é chamada de \"frase-semente\" ou \"frase de backup\".",
	"O termo \"Frase de Recuperação\" é comumente usado no contexto das carteiras de criptomoedas para se referir a uma sequência de palavras geradas pela sua carteira que lhe dá acesso aos fundos associados a essa carteira. Esta frase às vezes é chamada de \"frase-semente\" ou \"frase de backup\".",
	"Il termine \"frase di recupero\" è comunemente usato nel contesto dei portafogli di criptovaluta per riferirsi a una sequenza di parole generate dal tuo portafoglio che ti danno accesso ai fondi associati a quel portafoglio. Questa frase a volte è chiamata \"frase seed\" o \"frase di backup\".",
	"Der Begriff \"Wiederherstellungsphrase\" wird häufig im Kontext von Kryptowährungs-Wallets verwendet und bezieht sich auf eine von Ihrem Wallet generierte Wortfolge, die Ihnen Zugang zu den mit diesem Wallet verbundenen Mitteln gewährt. Diese Phrase wird manchmal als \"Seed-Phrase\" oder \"Backup-Phrase\" bezeichnet.",
	"\"रिकवरी वाक्यांश\" शब्द का सामान्यतः क्रिप्टोकरेंसी वॉलेट्स के संदर्भ में उपयोग किया जाता है, जो आपके वॉलेट द्वारा उत्पन्न शब्दों की एक श्रृंखला को संदर्भित करता है, जो आपको उस वॉलेट से संबंधित निधियों तक पहुंच प्रदान करता है। इस वाक्यांश को कभी-कभी \"सीड वाक्यांश\" या \"बैकअप वाक्यांश\" कहा जाता है।",
	"Термин \"Сэргээх үг\" нь криптовалютын түрийвчний контекстэд өргөн хэрэглэгддэг бөгөөд таны түрийвчээс үүсгэгдсэн үгсийн дараалалд хамаарна. Энэ нь тухайн түрийвчтэй холбогдсон санхүүгийн нөөцийг ашиглах боломжийг танд олгодог. Энэ үгийг заримдаа \"үрийн үг\" эсвэл \"нөөцийн үг\" гэж нэрлэдэг.",
	"คำว่า \"วลีการกู้คืน\" มักใช้ในบริบทของกระเป๋าเงินสกุลเงินดิจิทัลเพื่ออ้างถึงลำดับของคำที่สร้างโดยกระเป๋าเงินของคุณซึ่งให้การเข้าถึงเงินที่เชื่อมโยงกับกระเป๋าเงินนั้น วลีนี่บางครั้งเรียกว่า \"วลีเมล็ดพันธุ์\" หรือ \"วลีสำรอง\".",
	"Термін \"фраза відновлення\" часто використовується в контексті криптовалютних гаманців для позначення послідовності слів, згенерованих вашим гаманцем, яка надає доступ до коштів, пов'язаних з цим гаманцем. Цю фразу іноді називають \"seed-фразою\" або \"фразою резервного копіювання\".",
	"Cụm từ \"Câu khôi phục\" thường được sử dụng trong ngữ cảnh ví tiền điện tử để chỉ một chuỗi các từ do ví của bạn tạo ra, giúp bạn truy cập vào các quỹ liên kết với ví đó. Cụm từ này đôi khi được gọi là \"câu seed\" hoặc \"câu dự phòng\".",
	"Istilah \"Frasa Pemulihan\" umumnya digunakan dalam konteks dompet kripto untuk merujuk pada rangkaian kata yang dihasilkan oleh dompet Anda yang memberi Anda akses ke dana yang terkait dengan dompet tersebut. Frasa ini kadang-kadang disebut \"frasa seed\" atau \"frasa cadangan\".",
	"Ang terminong \"Recovery Phrase\" ay karaniwang ginagamit sa konteksto ng mga cryptocurrency wallet upang tukuyin ang isang sunud-sunod na mga salita na binuo ng iyong wallet na nagbibigay sa iyo ng access sa mga pondo na nauugnay sa wallet na iyon. Ang parirala na ito ay minsang tinatawag na \"seed phrase\" o \"backup phrase.\"",
	"\"রিসেট ডিভাইস\" শব্দটি সাধারণত ক্রিপ্টোকারেন্সি ওয়ালেটের প্রেক্ষাপটে ব্যবহৃত হয়, যা আপনার ওয়ালেট দ্বারা উত্পন্ন একটি সিরিজ শব্দের জন্য উল্লেখ করে যা আপনাকে সেই ওয়ালেটের সাথে সংযুক্ত তহবিলগুলিতে প্রবেশাধিকার দেয়। এই শব্দগুচ্ছটি কখনও কখনও \"বীজ বাক্যাংশ\" বা \"ব্যাকআপ বাক্যাংশ\" নামেও পরিচিত।"
};
const char* language_table_general[] = {
	"General",
	"通用",
	"通用",
	"Général",
	"General",
	"عام",
	"一般",
	"Общее",
	"일반",
	"Geral",
	"Geral",
	"Generale",
	"Allgemein",
	"सामान्य",
	"Ерөнхий",
	"ทั่วไปร",
	"Загальні",
	"Chung",
	"Umum",
	"Pangkalahatan",
	"সাধারণ"
};
const char* language_table_guide[] = {
	"Guide",
	"指南",
	"指南",
	"Guide",
	"Guía",
	"دليل",
	"ガイド",
	"Гид",
	"가이드",
	"Guia",
	"Guia",
	"Guida",
	"Anleitung",
	"मार्गदर्शक",
	"Удирдамж",
	"คู่มือ",
	"Керівництво",
	"Hướng dẫn",
	"Panduan",
	"Gabay",
	"নির্দেশিকা"
};

const char* language_table_settings[] = {
	"Settings",
	"设置",
	"設置",
	"Paramètres",
	"Configuración",
	"الإعدادات",
	"設定",
	"Настройки",
	"설정",
	"Configurações",
	"Configurações",
	"Impostazioni",
	"Einstellungen",
	"सेटिंग्स",
	"Тохиргоо",
	"การตั้งค่า",
	"Налаштування",
	"Cài đặt",
	"Pengaturan",
	"Mga setting",
	"সেটিংস"
};

const char* language_table_nfts[] = {
	"NFTs",
	"NFTs",
	"NFTs",
	"NFTs",
	"NFTs",
	"NFTs",
	"NFTs",
	"NFTs",
	"NFTs",
	"NFTs",
	"NFTs",
	"NFTs",
	"NFTs",
	"NFTs",
	"NFTs",
	"NFTs",
	"NFTs",
	"NFTs",
	"NFTs",
	"NFTs",
	"NFTs",
};

const char* language_table_conection_app_wallet[] = {
	"Connect App Wallet",
	"连接应用钱包",
	"連接應用錢包",
	"Connecter Wallet",
	"Conectar Monedero",
	"توصيل المحفظة",
	"ウォレット接続",
	"Подключить кошелек",
	"앱 지갑 연결",
	"Conectar Carteira",
	"Conectar Carteira",
	"Connetti Portafoglio",
	"Wallet verbinden",
	"ऐप वॉलेट से कनेक्ट करें",
	"Хэтэвч холбох",
	"เชื่อมต่อกระเป๋าเงิน",
	"Підключити гаманець",
	"Kết nối ví",
	"Hubungkan Dompet",
	"Wallet Ikonekta",
	"ওয়ালেট সংযোগ"
};

const char* language_table_minute[] = {
	"minute",
	"分钟",
	"分鐘",
	"minute",
	"minuto",
	"دقيقة",
	"分",
	"минута",
	"분",
	"minuto",
	"minuto",
	"minuto",
	"Minute",
	"मिनट",
	"минут",
	"นาที",
	"хвилина",
	"phút",
	"menit",
	"minuto",
	"মিনিট"
};
const char* language_table_device_shutdown[] = {
	"The device will never shut down.",
	"设备将永远不会关闭。",
	"设备永遠不會關閉。",
	"Dispositif ne s'éteindra jamais.",
	"El dispositivo nunca se apagará.",
	"الجهاز لن يغلق أبدًا.",
	"デバイスは決してシャットダウンしません。",
	"Устройство никогда не выключится.",
	"장치는 절대 종료되지 않습니다.",
	"O dispositivo nunca desligará.",
	"O dispositivo nunca desligará.",
	"Il dispositivo non si spegnerà mai.",
	"Das Gerät wird niemals heruntergefahren.",
	"उपकरण कभी बंद नहीं होगा।",
	"Құрылғы ешқашан сөнбейді.",
	"อุปกรณ์จะไม่ปิดตัวลงตลอดไป。",
	"Пристрій ніколи не вимкнеться.",
	"Thiết bị sẽ không bao giờ tắt.",
	"Ang aparato ay hindi kailanman magsasara.",
	"যন্ত্রটি কখনই বন্ধ হবে না।"
};

const char* language_table_during_device_locked_screen_off[] = {
	"During the device locked (screen off), it will shut down after %d minutes of inactivity.",
	"在设备锁定（屏幕关闭）期间，如果 %d 分钟没有操作，设备将自动关闭。",
	"在設備鎖定（屏幕關閉）期間，如果 %d 分鐘沒有操作，設備將自動關閉。",
	"Pendant que l'appareil est verrouillé (écran éteint), il s'éteindra après %d minutes d'inactivité.",
	"Durante el bloqueo del dispositivo (pantalla apagada), se apagará después de %d minutos de inactividad.",
	"أثناء قفل الجهاز (إيقاف الشاشة)، سيتم إيقاف التشغيل بعد %d دقائق من عدم النشاط.",
	"デバイスがロックされている（画面オフ）間、%d分間操作がないとシャットダウンします。",
	"Во время блокировки устройства (экран выключен) оно выключится через %d минут бездействия.",
	"장치가 잠겨 있는 동안 (화면 꺼짐), %d분 동안 아무런 활동이 없으면 종료됩니다.",
	"Durante o bloqueio do dispositivo (tela desligada), ele será desligado após %d minutos de inatividade.",
	"Durante o bloqueio do dispositivo (tela desligada), ele será desligado após %d minutos de inatividade.",
	"Durante il blocco del dispositivo (schermo spento), si spegnerà dopo %d minuti di inattività.",
	"Während der Gerätesperre (Bildschirm aus) wird es nach %d Minuten Inaktivität heruntergefahren.",
	"डिवाइस लॉक होने (स्क्रीन बंद) के दौरान, %d मिनट की निष्क्रियता के बाद यह बंद हो जाएगा।",
	"Төхөөрөмж түгжигдсэн үед (дэлгэц унтраалттай) %d минут идэвхигүй байвал унтарна.",
	"ในระหว่างที่อุปกรณ์ถูกล็อค (หน้าจอดับ) จะปิดเครื่องหลังจากไม่มีการใช้งานเป็นเวลา %d นาที.",
	"Під час блокування пристрою (екран вимкнено) він вимкнеться через %d хвилин бездіяльності.",
	"Trong khi thiết bị bị khóa (màn hình tắt), nó sẽ tắt sau %d phút không hoạt động.",
	"Selama perangkat terkunci (layar mati), perangkat akan mati setelah %d menit tidak aktif.",
	"Kapag naka-lock ang device (naka-off ang screen), mag-o-off ito pagkatapos ng %d minutong kawalan ng aktibidad.",
	"ডিভাইসটি লক থাকা অবস্থায় (স্ক্রিন বন্ধ), %d মিনিটের নিষ্ক্রিয়তার পরে এটি বন্ধ হয়ে যাবে।"
};

const char* language_table_auto_lock[] = {
	"Auto-Lock",
	"自动锁定",
	"自動鎖定",
	"Verrouillage automatique",
	"Bloqueo automático",
	"القفل التلقائي",
	"自動ロック",
	"Автоблокировка",
	"자동 잠금",
	"Bloqueio automático",
	"Bloqueio automático",
	"Blocco automatico",
	"Automatische Sperre",
	"स्वतः लॉक",
	"Автомат түгжих",
	"ล็อคอัตโนมัติ",
	"Автоблокування",
	"Tự động khóa",
	"Pengunci Otomatis",
	"Awtomatikong lock",
	"স্বয়ংক্রিয় লক"
};

const char* language_table_never[] = {
	"Never",
	"从不",
	"従不",
	"Jamais",
	"Nunca",
	"أبدا",
	"決してない",
	"Никогда",
	"절대",
	"Nunca",
	"Nunca",
	"Mai",
	"Niemals",
	"कभी नहीं",
	"Хэзээ ч үгүй",
	"ไม่เคย",
	"Ніколи",
	"Không bao giờ",
	"Tidak pernah",
	"Huwag kailanman",
	"কখনও না"
};

const char* language_table_after_10_minutes_screen_off[] = {
	"After %d minutes of inactivity, the screen will turn off.",
	"%d分钟不活动后，屏幕将关闭。",
	"%d分鐘不活動後，屏幕將關閉。",
	"Après %d minutes d'inactivité, l'écran s'éteindra.",
	"Después de %d minutos de inactividad, la pantalla se apagará.",
	"بعد %d دقائق من عدم النشاط، سيتم إيقاف تشغيل الشاشة.",
	"%d分間操作しないと、画面が消えます。",
	"После %d минут бездействия экран выключится.",
	"%d분 동안 비활성화 상태면 화면이 꺼집니다.",
	"Após %d minutos de inatividade, a tela será desligada.",
	"Após %d minutos de inatividade, a tela será desligada.",
	"Dopo %d minuti di inattività, lo schermo si spegnerà.",
	"Nach %d Minuten Inaktivität wird der Bildschirm ausgeschaltet.",
	"%d मिनट की निष्क्रियता के बाद स्क्रीन बंद हो जाएगी。",
	"%d минут үйлдэл хийгдээгүй бол дэлгэц унтарна.",
	"หลังจากไม่ได้ใช้งาน %d นาที หน้าจอจะปิด。",
	"Після %d хвилин бездіяльності екран вимкнеться.",
	"Sau %d phút không hoạt động, màn hình sẽ tắt.",
	"Setelah %d menit tidak ada aktivitas, layar akan mati.",
	"Matapos ang %d minuto ng kawalan ng aktibidad, mamamatay ang screen.",
	"১০ মিনিট নিষ্ক্রিয়তার পরে স্ক্রীন বন্ধ হয়ে যাবে।"
};

const char* language_table_language[] = {
	"Language",
	"语言",
	"語言",
	"Langue",
	"Idioma",
	"اللغة",
	"言語",
	"Язык",
	"언어",
	"Idioma",
	"Idioma",
	"Lingua",
	"Sprache",
	"भाषा",
	"Хэл",
	"ภาษา",
	"Мова",
	"Ngôn ngữ",
	"Bahasa",
	"Wika",
	"ভাষা",
};

const char* language_table_shutdown[] = {
	"Shutdown",
	"关机",
	"關機",
	"Arrêt",
	"Apagar",
	"إيقاف التشغيل",
	"シャットダウン",
	"Выключение",
	"종료",
	"Desligar",
	"Desligar",
	"Spegnimento",
	"Ausschalten",
	"बंद",
	"Унтраах",
	"ปิดเครื่อง",
	"Завершення роботи",
	"Tắt máy",
	"Mematikan",
	"Pag-shutdown",
	"শাটডাউন"
};

const char* language_table_homescreen[] = {
	"Homescreen",
	"主屏幕",
	"主屏幕",
	"Écran d'accueil",
	"Pantalla de inicio",
	"الشاشة الرئيسية",
	"ホーム画面",
	"Домашний экран",
	"홈 화면",
	"Tela principal",
	"Tela principal",
	"Schermata Home",
	"Startbildschirm",
	"मुख्य स्क्रीन",
	"Нүүр дэлгэц",
	"หน้าจอหลัก",
	"Головний екран",
	"Màn hình chính",
	"Layar Beranda",
	"Homescreen",
	"হোমস্ক্রীন"
};

const char* language_table_lock_screen[] = {
	"Lock Screen",
	"锁屏",
	"鎖屏",
	"Écran de verrouillage",
	"Pantalla de bloqueo",
	"شاشة القفل",
	"ロック画面",
	"Экран блокировки",
	"잠금 화면",
	"Tela de bloqueio",
	"Tela de bloqueio",
	"Schermata di blocco",
	"Sperrbildschirm",
	"लॉक स्क्रीन",
	"Цоож дэлгэц",
	"หน้าจอล็อค",
	"Екран блокування",
	"Màn hình khóa",
	"Layar Kunci",
	"Screen Lock",
	"লক স্ক্রীন"
};

const char* language_table_home_screen[] = {
	"Home Screen",
	"主屏幕",
	"主屏幕",
	"Écran d'accueil",
	"Pantalla de inicio",
	"الشاشة الرئيسية",
	"ホーム画面",
	"Домашний экран",
	"홈 화면",
	"Tela principal",
	"Tela principal",
	"Schermata Home",
	"Startbildschirm",
	"मुख्य स्क्रीन",
	"Нүүр дэлгэц",
	"หน้าจอหลัก",
	"Головний екран",
	"Màn hình chính",
	"Layar Beranda",
	"Homescreen",
	"হোমস্ক্রীন"
};

const char* language_table_abort_import[] = {
	"Abort Import?",
	"中止导入？",
	"中止導入？",
	"Annuler l'import ?",
	"¿Abortar la importación?",
	"إلغاء الاستيراد؟",
	"インポート中止？",
	"Отменить импорт?",
	"가져오기 중단?",
	"Cancelar importação?",
	"Cancelar importação?",
	"Annulla importazione",
	"Import abbrechen?",
	"आयात रद्द करें?",
	"Импортлохыг болих уу?",
	"ยกเลิกการนำเข้า?",
	"Скасувати імпорт?",
	"Hủy nhập",
	"Batalkan Impor?",
	"I-abort ang pag-import?",
	"আমদানি বাতিল?"
};

const char* language_table_sure_to_abort_process[] = {
	"Are you sure to abort this process? All progress will be lost.",
	"您确定要中止此过程吗？所有进度将丢失。",
	"您確定要中止此過程嗎？所有進度將丟失。",
	"Êtes-vous sûr d'annuler ce processus ? Tous les progrès seront perdus.",
	"¿Está seguro de abortar este proceso? Todo el progreso se perderá.",
	"هل أنت متأكد من إلغاء هذه العملية؟ سيتم فقدان جميع التقدم.",
	"このプロセスを中止してもよろしいですか？すべての進捗が失われます。",
	"Вы уверены, что хотите прервать этот процесс? Все данные будут потеряны.",
	"이 과정을 중단하시겠습니까? 모든 진행 내용이 손실됩니다.",
	"Tem certeza de que deseja interromper este processo? Todo o progresso será perdido.",
	"Tem certeza de que deseja interromper este processo? Todo o progresso será perdido.",
	"Sei sicuro di voler interrompere questo processo? Tutti i progressi saranno persi.",
	"Sind Sie sicher, dass Sie diesen Vorgang abbrechen möchten? Alle Fortschritte gehen verloren.",
	"क्या आप इस प्रक्रिया को छोड़ने के लिए निश्चित हैं? सभी प्रगति खो जाएगी。",
	"Та энэ процессыг зогсоохдоо итгэлтэй байна уу? Бүх явц алдагдах болно.",
	"คุณแน่ใจหรือไม่ว่าจะยกเลิกกระบวนการนี้ ความคืบหน้าทั้งหมดจะหายไป。",
	"Ви впевнені, що хочете скасувати цей процес? Усі зміни буде втрачено.",
	"Bạn có chắc chắn muốn hủy quy trình này không? Tất cả tiến trình sẽ bị mất.",
	"Anda yakin ingin membatalkan proses ini? Semua kemajuan akan hilang.",
	"Sigurado ka bang i-a-abort ang prosesong ito? Mawawala ang lahat ng progreso.",
	"আপনি কি নিশ্চিত যে এই প্রক্রিয়াটি বাতিল করবেন? সমস্ত অগ্রগতি হারিয়ে যাবে।"
};

const char* language_table_confirm[] = {
	"Confirm",
	"确认",
	"確認",
	"Confirmer",
	"Confirmar",
	"تأكيد",
	"確認",
	"Подтвердить",
	"확인",
	"Confirmar",
	"Confirmar",
	"Conferma",
	"Bestätigen",
	"पुष्टि करें",
	"Батлах",
	"ยืนยัน",
	"Підтвердити",
	"Xác nhận",
	"Konfirmasi",
	"Kumpirmahin",
	"নিশ্চিত করুন"
};

const char* language_table_import_recovery_phrase[] = {
	"Import recovery phrase to restore existing wallet. Enter the words in order, making sure they are in the same order as your recovery phrase backup.",
	"导入恢复短语以恢复现有钱包。按顺序输入单词，确保它们与您的恢复短语备份中的顺序相同。",
	"導入恢復短語以恢復現有錢包。按順序輸入單詞，確保它們與您的恢復短語備份中的順序相同。",
	"Importez la phrase de récupération pour restaurer le portefeuille existant. Entrez les mots dans l'ordre, en vous assurant qu'ils sont dans le même ordre que votre sauvegarde de phrase de récupération.",
	"Importe la frase de recuperación para restaurar la billetera existente. Introduzca las palabras en orden, asegurándose de que estén en el mismo orden que la copia de seguridad de su frase de recuperación.",
	"استيراد عبارة الاسترداد لاستعادة المحفظة الحالية. أدخل الكلمات بالترتيب، وتأكد من أنها بنفس ترتيب نسخة العبارة الاحتياطية.",
	"既存のウォレットを復元するためにリカバリフレーズをインポートします。リカバリフレーズのバックアップと同じ順序で単語を入力してください。",
	"Импортируйте фразу восстановления, чтобы восстановить существующий кошелек. Введите слова в том же порядке, что и в вашей резервной копии фразы восстановления.",
	"복구 문구를 가져와 기존 지갑을 복원하세요. 단어를 순서대로 입력하여 복구 문구 백업과 동일한 순서인지 확인하십시오.",
	"Importe a frase de recuperação para restaurar a carteira existente. Insira as palavras na ordem, certificando-se de que estão na mesma ordem que o backup da sua frase de recuperação.",
	"Importe a frase de recuperação para restaurar a carteira existente. Insira as palavras na ordem, certificando-se de que estão na mesma ordem que o backup da sua frase de recuperação.",
	"Importa la frase di recupero per ripristinare il portafoglio esistente. Inserisci le parole in ordine, assicurandoti che siano nello stesso ordine del backup della tua frase di recupero.",
	"Importieren Sie die Wiederherstellungsphrase, um die bestehende Wallet wiederherzustellen. Geben Sie die Wörter in der richtigen Reihenfolge ein und stellen Sie sicher, dass sie mit dem Backup Ihrer Wiederherstellungsphrase übereinstimmen.",
	"मौजूदा वॉलेट को पुनर्स्थापित करने के लिए रिकवरी वाक्यांश आयात करें। शब्दों को उसी क्रम में दर्ज करें, सुनिश्चित करें कि वे आपके रिकवरी वाक्यांश बैकअप के समान क्रम में हैं。",
	"Одоогийн түрийвчийг сэргээхийн тулд сэргээх үгийг импортлоно уу. Үгсийг дарааллаар нь оруулаарай, нөөц үгийнхээ дараалалтай адил байгаа эсэхийг шалгаарай.",
	"นำเข้าวลีการกู้คืนเพื่อกู้คืนกระเป๋าสตางค์ที่มีอยู่ ป้อนคำตามลำดับโดยตรวจสอบให้แน่ใจว่าเรียงลำดับเหมือนกับการสำรองข้อมูลวลีการกู้คืนของคุณ。",
	"Імпортуйте фразу для відновлення, щоб відновити існуючий гаманець. Введіть слова у правильному порядку, переконайтесь, що вони співпадають із резервною копією вашої фрази для відновлення.",
	"Nhập cụm từ khôi phục để khôi phục ví hiện có. Nhập các từ theo thứ tự, đảm bảo rằng chúng giống với thứ tự trong bản sao lưu cụm từ khôi phục của bạn.",
	"Impor frasa pemulihan untuk memulihkan dompet yang ada. Masukkan kata-kata secara berurutan, pastikan mereka dalam urutan yang sama seperti cadangan frasa pemulihan Anda.",
	"I-import ang recovery phrase upang i-restore ang existing wallet. I-enter ang mga salita ayon sa pagkakasunod-sunod, siguraduhing pareho ang pagkakasunud-sunod sa iyong recovery phrase backup.",
	"বিদ্যমান ওয়ালেট পুনরুদ্ধার করতে পুনরুদ্ধার বাক্যাংশ আমদানি করুন। শব্দগুলি ক্রমানুসারে প্রবেশ করুন, নিশ্চিত করুন যে সেগুলি আপনার পুনরুদ্ধার বাক্যাংশ ব্যাকআপের সাথে একই ক্রমে রয়েছে。"
};

const char* language_table_enter_word[] = {
	"Enter Word",
	"输入单词",
	"輸入單詞",
	"Saisir le mot:",
	"Ingreso la palabra",
	"أدخل الكلمة",
	"単語 #%d を入力",
	"Введите слово:",
	"단어 입력",
	"Insira a palavra",
	"Insira a palavra",
	"Inserisci la parola",
	"Geben Sie Wort ein:",
	"शब्द दर्ज करें:",
	"Үг оруулна уу:",
	"ป้อนคำ",
	"Введіть слово:",
	"Nhập từ",
	"Masukkan Kata",
	"Ipasok ang Salita",
	"শব্দ লিখুন:"
};

const char* language_table_successfully_recovered_wallet[] = {
	"You have successfully recovered your wallet.",
	"您已成功恢复钱包。",
	"您已成功恢復錢包。",
	"Vous avez récupéré votre portefeuille avec succès.",
	"Ha recuperado su billetera con éxito.",
	"لقد قمت باستعادة محفظتك بنجاح.",
	"ウォレットの復元に成功しました。",
	"Вы успешно восстановили свой кошелек.",
	"지갑을 성공적으로 복구했습니다.",
	"Você recuperou sua carteira com sucesso.",
	"Você recuperou sua carteira com sucesso.",
	"Hai recuperato con successo il tuo portafoglio.",
	"Sie haben Ihr Wallet erfolgreich wiederhergestellt.",
	"आपने सफलतापूर्वक अपना वॉलेट पुनर्प्राप्त कर लिया है।",
	"Та амжилттай хэтэвчээ сэргээсэн байна.",
	"คุณกู้คืนกระเป๋าเงินสำเร็จแล้ว.",
	"Ви успішно відновили свій гаманець.",
	"Bạn đã khôi phục thành công ví của mình.",
	"Anda berhasil memulihkan dompet Anda.",
	"Matagumpay mong na-recover ang iyong wallet.",
	"আপনি সফলভাবে আপনার ওয়ালেট পুনরুদ্ধার করেছেন。"
};

const char* language_table_security[] = {
	"Security",
	"安全",
	"安全",
	"Sécurité",
	"Seguridad",
	"الأمان",
	"セキュリティ",
	"Безопасность",
	"보안",
	"Segurança",
	"Segurança",
	"Sicurezza",
	"Sicherheit",
	"सुरक्षा",
	"Аюулгүй байдал",
	"ความปลอดภัย",
	"Безпека",
	"Bảo mật",
	"Keamanan",
	"Seguridad",
	"নিরাপত্তা"
};

const char* language_table_about_device[] = {
	"About Device",
	"关于设备",
	"關於設備",
	"À propos de l'appareil",
	"Acerca del dispositivo",
	"حول الجهاز",
	"デバイスについて",
	"О устройстве",
	"디바이스 정보",
	"Sobre o dispositivo",
	"Sobre o dispositivo",
	"Informazioni sul dispositivo",
	"Über das Gerät",
	"डिवाइस के बारे में",
	"Төхөөрөмжийн тухай",
	"เกี่ยวกับอุปกรณ์",
	"Про пристрій",
	"Về thiết bị",
	"Tentang Perangkat",
	"Tungkol sa Device",
	"ডিভাইস সম্পর্কে"
};

const char* language_table_power_off[] = {
	"Power off",
	"关机",
	"關機",
	"Éteindre",
	"Apagar",
	"إيقاف التشغيل",
	"電源を切る",
	"Выключить",
	"전원 끄기",
	"Desligar",
	"Desligar",
	"Spegnere",
	"Ausschalten",
	"पावर ऑफ",
	"Унтраах",
	"ปิดเครื่อง",
	"Вимкнути",
	"Tắt nguồn",
	"Matikan",
	"Patayin",
	"শাটডাউন"
};

const char* language_table_change_pin[] = {
	"Change PIN",
	"更改PIN码",
	"更改PIN碼",
	"Changer le code PIN",
	"Cambiar PIN",
	"تغيير رمز PIN",
	"PINコードを変更する",
	"Изменить PIN-код",
	"PIN 변경",
	"Alterar PIN",
	"Alterar PIN",
	"Cambia PIN",
	"PIN ändern",
	"PIN बदलें",
	"PIN кодыг өөрчлөх",
	"เปลี่ยน PIN",
	"Змінити PIN",
	"Thay đổi PIN",
	"Ubah PIN",
	"Baguhin ang PIN",
	"PIN পরিবর্তন করুন"
};

const char* language_table_set_pin_protect_wallet[] = {
    "Set a 6 to 50-digits length PIN to protect your wallet.",
    "设置一个6到50位长度的PIN码以保护您的钱包。",
    "設置一個6到50位長度的PIN碼以保護您的錢包。",
    "Définissez un code PIN de 6 à 50 chiffres pour protéger votre portefeuille.",
    "Establezca un PIN de 6 a 50 dígitos para proteger su billetera.",
    "قم بتعيين رقم تعريف شخصي (PIN) يتراوح بين 6 إلى 50 رقمًا لحماية محفظتك.",
    "ウォレットを保護するために6〜50桁のPINを設定してください。",
    "Установите PIN-код длиной от 6 до 50 цифр для защиты вашего кошелька.",
    "지갑을 보호하기 위해 6에서 50자리 길이의 PIN을 설정하세요.",
    "Defina um PIN de 6 a 50 dígitos para proteger sua carteira.",
    "Defina um PIN de 6 a 50 dígitos para proteger sua carteira.",
    "Imposta un PIN da 6 a 50 cifre per proteggere il tuo portafoglio.",
    "Richten Sie eine PIN mit einer Länge von 6 bis 50 Ziffern ein, um Ihre Wallet zu schützen.",
    "अपने वॉलेट की सुरक्षा के लिए 6 से 50 अंकों की लंबाई का पिन सेट करें।",
    "Таны түрийвчийг хамгаалахын тулд 6-50 оронтой ПИН код тохируулаарай.",
    "ตั้งค่ารหัส PIN ความยาว 6 ถึง 50 หลักเพื่อปกป้องกระเป๋าเงินของคุณ。",
    "Встановіть PIN-код довжиною від 6 до 50 цифр для захисту вашого гаманця.",
    "Đặt mã PIN dài từ 6 đến 50 chữ số để bảo vệ ví của bạn.",
    "Tetapkan PIN dengan panjang 6 hingga 50 digit untuk melindungi dompet Anda.",
    "Magtakda ng PIN na may habang 6 hanggang 50 digit upang protektahan ang iyong wallet.",
    "আপনার ওয়ালেট সুরক্ষার জন্য ৬ থেকে ৫০-ডিজিটের একটি পিন সেট করুন।",
};


const char* language_table_enter_old_pin[] = {
	"Enter Old PIN",
	"输入旧PIN码",
	"輸入舊PIN碼",
	"Entrez l'ancien PIN",
	"Ingrese el PIN anterior",
	"أدخل رقم التعريف الشخصي القديم",
	"古いPINコードを入力",
	"Введите старый PIN",
	"기존 PIN 입력",
	"Insira o PIN antigo",
	"Insira o PIN antigo",
	"Inserisci il PIN vecchio",
	"Alten PIN eingeben",
	"पुराना पिन दर्ज करें",
	"Хуучин PIN кодоо оруулна уу",
	"ใส่รหัสผ่านเดิม",
	"Введіть старий PIN",
	"Nhập PIN cũ",
	"Masukkan PIN lama",
	"Ipasok ang Lumang PIN",
	"পুরানো পিন লিখুন"
};

const char* language_table_set_new_pin[] = {
	"Set New PIN",
	"设置新PIN码",
	"設置新PIN碼",
	"Définir un nouveau PIN",
	"Establecer un nuevo PIN",
	"تعيين رقم تعريف شخصي جديد",
	"新しいPINコードを設定",
	"Установить новый PIN",
	"새 PIN 설정",
	"Definir novo PIN",
	"Definir novo PIN",
	"Imposta nuovo PIN",
	"Neuen PIN festlegen",
	"नया पिन सेट करें",
	"Шинэ PIN код тохируулах",
	"ตั้ง PIN ใหม่",
	"Встановити новий PIN",
	"Đặt mã PIN mới",
	"Tetapkan PIN baru",
	"Itakda ang Bagong PIN",
	"নতুন পিন সেট করুন"
};

const char* language_table_pin_changed[] = {
	"PIN Changed",
	"PIN码已更改",
	"PIN碼已更改",
	"PIN modifié",
	"PIN cambiado",
	"تم تغيير رقم التعريف الشخصي",
	"PINが変更されました",
	"PIN изменен",
	"PIN이 변경됨",
	"PIN alterado",
	"PIN alterado",
	"PIN modificato",
	"PIN geändert",
	"पिन बदल गया है",
	"PIN код солигдсон",
	"เปลี่ยน PIN แล้ว",
	"PIN змінено",
	"PIN đã được thay đổi",
	"PIN telah diubah",
	"Nabago ang PIN",
	"পিন পরিবর্তিত হয়েছে"
};

const char* language_table_successfully_changed_pin[] = {
	"You have successfully changed your PIN.",
	"您已成功更改PIN码",
	"您已成功更改PIN碼",
	"Vous avez réussi à changer votre PIN.",
	"Ha cambiado su PIN correctamente.",
	"لقد نجحت في تغيير رقم التعريف الشخصي الخاص بك",
	"PINの変更が成功しました",
	"Вы успешно изменили PIN",
	"PIN을 성공적으로 변경했습니다",
	"Você alterou seu PIN com sucesso",
	"Você alterou seu PIN com sucesso",
	"Hai cambiato con successo il PIN",
	"Sie haben Ihre PIN erfolgreich geändert",
	"आपने सफलतापूर्वक पिन बदल दिया है",
	"Та PIN кодоо амжилттай сольсон байна",
	"คุณได้เปลี่ยน PIN เรียบร้อยแล้ว",
	"Ви успішно змінили свій PIN",
	"Bạn đã thay đổi PIN thành công",
	"Anda telah berhasil mengubah PIN",
	"Matagumpay mong nabago ang PIN",
	"আপনি সফলভাবে পিন পরিবর্তন করেছেন"
};

const char* language_table_done[] = {
	"Done",
	"完成",
	"完成",
	"Terminé",
	"Hecho",
	"تم",
	"完了",
	"Готово",
	"완료",
	"Concluído",
	"Concluído",
	"Fatto",
	"Fertig",
	"हो गया",
	"Болсон",
	"เสร็จสิ้น",
	"Готово",
	"Xong",
	"Selesai",
	"Tapos",
	"সম্পন্ন"
};

const char* language_table_connect_app_wallet[] = {
	"Connect App Wallet",
	"连接应用钱包",
	"連接應用錢包",
	"Connecter Portefeuille de l'application",
	"Conectar billetera de la aplicación",
	"ربط المحفظة بالتطبيق",
	"アプリウォレットを接続",
	"Подключить кошелек приложения",
	"앱 지갑 연결",
	"Conectar Carteira App",
	"Conectar Carteira do Aplicativo",
	"Connetti Portafoglio App",
	"App-Wallet verbinden",
	"ऐप वॉलेट कनेक्ट करें",
	"Апп түрийвчийг холбох",
	"เชื่อมต่อกระเป๋าเงินแอพ",
	"Підключити додаток-гаманець",
	"Kết nối Ví ứng dụng",
	"Hubungkan Dompet Aplikasi",
	"I-konek ang App Wallet",
	"অ্যাপ ওয়ালেট সংযুক্ত করুন"
};

const char* language_table_bluetooth_pairing[] = {
	"Bluetooth Pairing and enter the pairing code on your device.",
	"蓝牙配对并在您的设备上输入配对码。",
	"藍牙配對並在您的設備上輸入配對碼。",
	"Appairage Bluetooth et saisissez le code de jumelage sur votre appareil.",
	"Emparejamiento Bluetooth e ingrese el código de emparejamiento en su dispositivo.",
	"اقتران Bluetooth وأدخل رمز الاقتران على جهازك.",
	"Bluetoothペアリングを行い、お使いのデバイスにペアリングコードを入力してください。",
	"Пара Bluetooth и введите код сопряжения на вашем устройстве.",
	"블루투스 페어링을 하고 장치에서 페어링 코드를 입력하세요.",
	"Emparelhamento Bluetooth e insira o código de emparelhamento no seu dispositivo.",
	"Emparelhamento Bluetooth e insira o código de emparelhamento no seu dispositivo.",
	"Associazione Bluetooth e inserisci il codice di abbinamento sul tuo dispositivo.",
	"Bluetooth-Kopplung und geben Sie den Pairing-Code auf Ihrem Gerät ein.",
	"ब्लूटूथ पेयरिंग और अपने डिवाइस पर पेयरिंग कोड दर्ज करें।",
	"Bluetooth хослолыг тохируулж, төхөөрөмж дээрээ хослох кодоо оруулна уу.",
	"การจับคู่บลูทูธและป้อนรหัสการจับคู่บนอุปกรณ์ของคุณ。",
	"Підключення через Bluetooth і введіть код підключення на вашому пристрої.",
	"Ghép nối Bluetooth và nhập mã ghép nối trên thiết bị của bạn.",
	"Pemasangan Bluetooth dan masukkan kode pemasangan di perangkat Anda.",
	"Bluetooth Pairing at ilagay ang pairing code sa iyong device.",
	"ব্লুটুথ পেয়ারিং এবং আপনার ডিভাইসে পেয়ারিং কোড প্রবেশ করুন।"
};

const char* language_table_change_password[] = {
	"Change Password",
	"更改密码",
	"更改密碼",
	"Changer le mot de passe",
	"Cambiar contraseña",
	"تغيير كلمة المرور",
	"パスワードを変更",
	"Изменить пароль",
	"비밀번호 변경",
	"Alterar senha",
	"Alterar senha",
	"Cambia la password",
	"Passwort ändern",
	"पासवर्ड बदलें",
	"Нууц үг солих",
	"เปลี่ยนรหัสผ่าน",
	"Змінити пароль",
	"Đổi mật khẩu",
	"Ganti Kata Sandi",
	"Baguhin ang Password",
	"পাসওয়ার্ড পরিবর্তন"
};

const char* language_table_reset_device[] = {
	"Reset Device",
	"重置设备",
	"重置設備",
	"Réinitialiser l’appareil",
	"Restablecer dispositivo",
	"إعادة ضبط الجهاز",
	"デバイスをリセット",
	"Сбросить устройство",
	"장치 재설정",
	"Reiniciar dispositivo",
	"Redefinir Dispositivo",
	"Resetta Dispositivo",
	"Gerät zurücksetzen",
	"डिवाइस रीसेट करें",
	"Төхөөрөмжийг дахин тохируулах",
	"รีเซ็ตอุปกรณ์",
	"Скинути пристрій",
	"Khôi phục thiết bị",
	"Setel Ulang Perangkat",
	"I-reset ang Device",
	"ডিভাইস রিসেট করুন"
};

const char* language_table_model[] = {
	"Model",
	"型号",
	"型號",
	"Modèle",
	"Modelo",
	"النموذج",
	"モデル",
	"Модель",
	"모델",
	"Modelo",
	"Modelo do Brasil",
	"Modello",
	"Modell",
	"मॉडल",
	"Загвар",
	"รุ่น",
	"Модель",
	"Mẫu",
	"Model",
	"Modelo",
	"মডেল"
};

const char* language_table_bluetooth_name[] = {
	"Bluetooth Name",
	"蓝牙名称",
	"藍牙名稱",
	"Nom Bluetooth",
	"Nombre de Bluetooth",
	"اسم البلوتوث",
	"Bluetooth名",
	"Имя Bluetooth",
	"블루투스 이름",
	"Nome do Bluetooth",
	"Nome do Bluetooth do Brasil",
	"Nome Bluetooth",
	"Bluetooth-Name",
	"ब्लूटूथ नाम",
	"Bluetooth нэр",
	"ชื่อบลูทูธ",
	"Ім'я Bluetooth",
	"Tên Bluetooth",
	"Nama Bluetooth",
	"Pangalan ng Bluetooth",
	"ব্লুটুথ নাম"
};

const char* language_table_system[] = {
	"System",
	"系统",
	"系統",
	"Système",
	"Sistema",
	"النظام",
	"システム",
	"Система",
	"시스템",
	"Sistema",
	"Sistema do Brasil",
	"Sistema",
	"System",
	"प्रणाली",
	"Систем",
	"ระบบ",
	"Система",
	"Hệ thống",
	"Sistem",
	"Sistema",
	"সিস্টেম" };

const char* language_table_bluetooth[] = {
	"Bluetooth",
	"蓝牙",
	"藍牙",
	"Bluetooth",
	"Bluetooth",
	"بلوتوث",
	"ブルートゥース",
	"Bluetooth",
	"블루투스",
	"Bluetooth",
	"Bluetooth do Brasil",
	"Bluetooth",
	"Bluetooth",
	"ब्लूटूथ",
	"Bluetooth",
	"บลูทูธ",
	"Bluetooth",
	"Bluetooth",
	"Bluetooth",
	"Bluetooth",
	"ব্লুটুথ"
};

const char* language_table_bootloader[] = {
	"Bootloader",
	"引导程序",
	"引導程序",
	"Chargeur de démarrage",
	"Cargador de arranque",
	"برنامج التحميل",
	"ブートローダー",
	"Загрузчик",
	"부트로더",
	"Carregador de Inicialização",
	"Carregador de Inicialização do Brasil",
	"Bootloader",
	"Bootloader",
	"बूटलोडर",
	"Ачаалагч",
	"บูตโหลดเดอร์",
	"Завантажувач",
	"Bộ nạp khởi động",
	"Bootloader",
	"Bootloader",
	"বুটলোডার"
};

const char* language_table_reset_to_factory_default[] = {
	"Reset your device to factory default. WARNING: This will remove all data from your device.",
	"将您的设备恢复为出厂默认设置。警告：这将删除设备上的所有数据。",
	"將您的設備恢復為出廠默認設置。警告：這將刪除設備上的所有數據。",
	"Réinitialisez votre appareil aux paramètres d'usine. AVERTISSEMENT : cela supprimera toutes les données de votre appareil.",
	"Restablezca su dispositivo a la configuración de fábrica. ADVERTENCIA: Esto eliminará todos los datos de su dispositivo.",
	"إعادة تعيين جهازك إلى الإعدادات الافتراضية. تحذير: سيؤدي هذا إلى إزالة جميع البيانات من جهازك.",
	"デバイスを工場出荷時設定にリセットします。警告: これにより、デバイス内のすべてのデータが削除されます。",
	"Сбросьте настройки устройства до заводских. ВНИМАНИЕ: Это удалит все данные с вашего устройства.",
	"장치를 초기 설정으로 재설정하십시오. 경고: 이 작업은 장치의 모든 데이터를 삭제합니다.",
	"Redefina seu dispositivo para os padrões de fábrica. AVISO: Isso removerá todos os dados do seu dispositivo.",
	"Redefina seu dispositivo para as configurações de fábrica. AVISO: Isso removerá todos os dados do seu dispositivo.",
	"Ripristina il dispositivo alle impostazioni di fabbrica. AVVISO: Questo eliminerà tutti i dati dal dispositivo.",
	"Setzen Sie Ihr Gerät auf die Werkseinstellungen zurück. WARNUNG: Dadurch werden alle Daten von Ihrem Gerät entfernt.",
	"अपने डिवाइस को फ़ैक्टरी डिफ़ॉल्ट पर रीसेट करें। चेतावनी: इससे आपके डिवाइस से सभी डेटा हटा दिए जाएंगे。",
	"Төхөөрөмжөө үйлдвэрийн анхны тохиргоонд нь сэргээнэ үү. Анхаар: Энэ нь таны төхөөрөмж дээрх бүх мэдээллийг устгах болно.",
	"รีเซ็ตอุปกรณ์ของคุณเป็นค่าเริ่มต้นจากโรงงาน คำเตือน: สิ่งนี้จะลบข้อมูลทั้งหมดจากอุปกรณ์ของคุณ。",
	"Скиньте ваш пристрій до заводських налаштувань. УВАГА: Це видалить всі дані з вашого пристрою.",
	"Đặt lại thiết bị của bạn về mặc định của nhà sản xuất. CẢNH BÁO: Điều này sẽ xóa tất cả dữ liệu khỏi thiết bị của bạn.",
	"Setel ulang perangkat Anda ke default pabrik. PERINGATAN: Ini akan menghapus semua data dari perangkat Anda.",
	"I-reset ang iyong device sa factory default. BABALA: Mababura ang lahat ng data sa iyong device.",
	"আপনার ডিভাইসটি ফ্যাক্টরি ডিফল্টে রিসেট করুন। সতর্কতা: এটি আপনার ডিভাইসের সমস্ত ডেটা মুছে দেবে।"
};

const char* language_table_this_will_erase_all_data[] = {
	"This will erase all data on internal storage and Secure Element (SE). Beforehand, you need to know:",
	"这将擦除内置存储和安全元件 (SE) 上的所有数据。在此之前，您需要了解：",
	"這將擦除內置存儲和安全元件 (SE) 上的所有數據。在此之前，您需要了解：",
	"Cela effacera toutes les données sur le stockage interne et l'élément sécurisé (SE). Auparavant, vous devez savoir :",
	"Esto borrará todos los datos del almacenamiento interno y del Elemento Seguro (SE). Antes, debes saber:",
	"سيؤدي هذا إلى محو جميع البيانات الموجودة على وحدة التخزين الداخلية والعنصر الآمن (SE). من قبل، تحتاج إلى معرفة:",
	"これは、内部ストレージおよびセキュアエレメント（SE）上のすべてのデータを消去します。事前に知っておくべきこと:",
	"Это сотрет все данные на внутреннем хранилище и Secure Element (SE). До этого вам нужно знать:",
	"이 작업은 내부 저장소 및 보안 요소(SE)에 있는 모든 데이터를 지웁니다. 미리 알아야 할 사항:",
	"Isso apagará todos os dados no armazenamento interno e no Elemento Seguro (SE). Antes disso, você precisa saber:",
	"Isso apagará todos os dados do armazenamento interno e do Elemento Seguro (SE). Antes disso, você precisa saber:",
	"Questo cancellerà tutti i dati nella memoria interna e nell'Elemento Sicuro (SE). Prima, è necessario sapere:",
	"Dadurch werden alle Daten auf dem internen Speicher und dem Secure Element (SE) gelöscht. Vorab müssen Sie wissen:",
	"यह आपके आंतरिक स्टोरेज और सिक्योर एलिमेंट (SE) पर सभी डेटा मिटा देगा। पहले से आपको यह पता होना चाहिए:",
	"Энэ нь дотоод хадгалалт болон Secure Element (SE) дээрх бүх өгөгдлийг арилгах болно. Үүний өмнө мэдэж байх ёстой зүйлс:",
	"สิ่งนี้จะลบข้อมูลทั้งหมดบนที่เก็บข้อมูลภายในและ Secure Element (SE) ก่อนหน้านี้คุณต้องทราบว่า:",
	"Це зітре всі дані на внутрішньому сховищі та Secure Element (SE). Перед цим вам потрібно знати:",
	"Điều này sẽ xóa tất cả dữ liệu trên bộ nhớ trong và Phần tử Bảo mật (SE). Trước đó, bạn cần biết:",
	"Ini akan menghapus semua data di penyimpanan internal dan Secure Element (SE). Sebelumnya, Anda perlu tahu:",
	"Mabubura nito ang lahat ng data sa internal na storage at Secure Element (SE). Bago iyon, kailangan mong malaman:",
	"এটি অভ্যন্তরীণ স্টোরেজ এবং সিকিউর এলিমেন্ট (SE) এর সমস্ত ডেটা মুছে ফেলবে। এর আগে, আপনাকে জানতে হবে:"
};

const char* language_table_after_reset_phrase_will_be_deleted[] = {
	"After reset, the recovery phrase on this device will be permanently deleted.",
	"重置后，该设备上的恢复短语将被永久删除。",
	"重置後，該設備上的恢復短語將被永久刪除。",
	"Après réinitialisation, la phrase de récupération sur cet appareil sera définitivement supprimée.",
	"Después de reiniciar, la frase de recuperación en este dispositivo será eliminada permanentemente.",
	"بعد إعادة التعيين، سيتم حذف عبارة الاسترداد على هذا الجهاز بشكل دائم.",
	"リセット後、このデバイスのリカバリフレーズは永久に削除されます。",
	"После сброса, фраза восстановления на этом устройстве будет навсегда удалена.",
	"리셋 후, 이 장치의 복구 구문은 영구적으로 삭제됩니다.",
	"Após a redefinição, a frase de recuperação neste dispositivo será permanentemente excluída.",
	"Após a redefinição, a frase de recuperação neste dispositivo será permanentemente excluída.",
	"Dopo il ripristino, la frase di recupero su questo dispositivo sarà cancellata definitivamente.",
	"Nach dem Zurücksetzen wird die Wiederherstellungsphrase auf diesem Gerät dauerhaft gelöscht.",
	"रीसेट करने के बाद, इस डिवाइस पर रिकवरी वाक्यांश स्थायी रूप से हटा दिया जाएगा。",
	"Дахин тохируулсаны дараа энэ төхөөрөмж дээрх сэргээх хэллэгийг байнга устгана.",
	"หลังจากรีเซ็ตแล้ว วลีการกู้คืนในอุปกรณ์นี้จะถูกลบอย่างถาวร。",
	"Після скидання фраза відновлення на цьому пристрої буде видалена назавжди.",
	"Sau khi đặt lại, cụm từ khôi phục trên thiết bị này sẽ bị xóa vĩnh viễn.",
	"Setelah reset, frase pemulihan pada perangkat ini akan dihapus secara permanen.",
	"Pagkatapos ng pag-reset, ang recovery phrase sa device na ito ay permanenteng mabubura.",
	"রিসেটের পরে, এই ডিভাইসে রিকভারি ফ্রেজ স্থায়ীভাবে মুছে ফেলা হবে।"
};

const char* language_table_slide_to_reset[] = {
	"Slide to Reset",
	"滑动以重置",
	"滑動以重置",
	"Faites glisser pour réinitialiser",
	"Deslizar para reiniciar",
	"اسحب لإعادة التعيين",
	"リセットするにはスライド",
	"Проведите для сброса",
	"슬라이드하여 재설정",
	"Deslizar para redefinir",
	"Deslizar para redefinir",
	"Scorri per ripristinare",
	"Zum Zurücksetzen schieben",
	"रीसेट के लिए स्लाइड करें",
	"Сдвиньте для сброса",
	"리셋하려면 슬라이드",
	"Проведіть для скидання",
	"Kéo để đặt lại",
	"Geser untuk mengatur ulang",
	"I-slide upang i-reset",
	"স্লাইড করে রিসেট করুন"
};

const char* language_table_reset_complete[] = {
	"Reset Complete",
	"重置完成",
	"重置完成",
	"Réinitialisation terminée",
	"Restablecimiento completo",
	"إعادة تعيين كاملة",
	"リセット完了",
	"Сброс завершен",
	"재설정 완료",
	"Redefinição concluída",
	"Redefinição concluída",
	"Ripristino completato",
	"Zurücksetzen abgeschlossen",
	"रीसेट पूरा",
	"Сэргэсэн",
	"รีเซ็ตเสร็จสมบูรณ์",
	"Скидання завершено",
	"Đặt lại hoàn tất",
	"Reset selesai",
	"Tapos na ang Pag-reset",
	"রিসেট সম্পন্ন"
};

const char* language_table_device_reset[] = {
	"The device is reset, restart now.",
	"设备已重置，现在重启。",
	"設備已重置，立即重啟。",
	"L'appareil a été réinitialisé, redémarrez maintenant.",
	"El dispositivo se ha restablecido, reinicie ahora.",
	"تم إعادة تعيين الجهاز، أعد التشغيل الآن.",
	"デバイスがリセットされました。再起動してください。",
	"Устройство сброшено, перезапустите сейчас.",
	"장치가 초기화되었습니다. 지금 재시작하십시오.",
	"O dispositivo foi redefinido, reinicie agora.",
	"O dispositivo foi redefinido, reinicie agora.",
	"Il dispositivo è stato resettato, riavvia ora.",
	"Das Gerät wurde zurückgesetzt, jetzt neu starten.",
	"डिवाइस रीसेट हो गया है, अब पुनरारंभ करें।",
	"Төхөөрөмжийг дахин тохирууллаа, одоо дахин асаана уу.",
	"อุปกรณ์ได้รับการรีเซ็ตแล้ว กรุณารีสตาร์ท。",
	"Пристрій скинуто, перезавантажте зараз.",
	"Thiết bị đã được đặt lại, khởi động lại ngay bây giờ.",
	"Perangkat telah direset, mulai ulang sekarang.",
	"Na-reset ang device, i-restart ngayon.",
	"ডিভাইসটি রিসেট হয়েছে, এখন পুনরায় চালু করুন।"
};

const char* language_table_restart[] = {
	"Restart",
	"重启",
	"重啟",
	"Redémarrer",
	"Reiniciar",
	"إعادة التشغيل",
	"再起動",
	"Перезагрузить",
	"재시작",
	"Reiniciar",
	"Reiniciar",
	"Riavvia",
	"Neu starten",
	"पुनरारंभ करें",
	"Дахин асаах",
	"รีสตาร์ท",
	"Перезавантажити",
	"Khởi động lại",
	"Mulai ulang",
	"I-restart",
	"পুনরায় চালু করুন"
};

const char* language_table_address[] = {
	"Address",
	"地址",
	"地址",
	"Adresse",
	"Dirección",
	"العنوان",
	"住所",
	"Адрес",
	"주소",
	"Endereço",
	"Endereço",
	"Indirizzo",
	"Adresse",
	"पता",
	"Хаяг",
	"ที่อยู่",
	"Адреса",
	"Địa chỉ",
	"Alamat",
	"Tirahan",
	"ঠিকানা"
};

const char* language_table_path[] = {
	"Path",
	"路径",
	"路徑",
	"Chemin",
	"Ruta",
	"مسار",
	"パス",
	"Путь",
	"경로",
	"Caminho",
	"Caminho",
	"Percorso",
	"Pfad",
	"मार्ग",
	"Зам",
	"เส้นทาง",
	"Шлях",
	"Đường dẫn",
	"Jalur",
	"Daan",
	"পথ"
};

const char* language_table_qr_code[] = {
	"QR code",
	"二维码",
	"二維碼",
	"Code QR",
	"Código QR",
	"رمز الاستجابة السريعة",
	"QRコード",
	"QR-код",
	"QR코드",
	"Código QR",
	"Código QR",
	"Codice QR",
	"QR-Code",
	"क्यूआर कोड",
	"QR код",
	"คิวอาร์โค้ด",
	"QR-код",
	"Mã QR",
	"Kode QR",
	"Kodigo QR",
	"QR কোড"
};

const char* language_table_view_transaction[] = {
	"View Transaction",
	"查看交易",
	"查看交易",
	"Voir la transaction",
	"Ver Transacción",
	"عرض المعاملة",
	"取引を見る",
	"Просмотреть транзакцию",
	"거래 보기",
	"Ver Transação",
	"Ver Transação",
	"Visualizza transazione",
	"Transaktion anzeigen",
	"लेन-देन देखें",
	"Харагдах гүйлгээ",
	"ดูธุรกรรม",
	"Переглянути транзакцію",
	"Xem giao dịch",
	"Lihat Transaksi",
	"Tingnan ang Transaksyon",
	"লেনদেন দেখুন"
};

const char* language_table_directions[] = {
	"Directions",
	"指引",
	"指引",
	"Directions",
	"Direcciones",
	"التوجيهات",
	"指示",
	"Направления",
	"지시 사항",
	"Direções",
	"Direções do Brasil",
	"Direzioni",
	"Anweisungen",
	"दिशानिर्देश",
	"Зөвлөмж",
	"คำแนะนำ",
	"Напрями",
	"Hướng dẫn",
	"Petunjuk",
	"Mga Direksyon",
	"निर्देशन"
};

const char* language_table_fee[] = {
	"Fee",
	"费用",
	"費用",
	"Frais",
	"Tasas",
	"رسوم",
	"手数料",
	"Сборы",
	"수수료",
	"Taxas",
	"Taxas",
	"Tassa",
	"Gebühren",
	"शुल्क",
	"Тариф",
	"ค่าธรรมเนียม",
	"Збір",
	"Phí",
	"Biaya",
	"Bayarin",
	"ফি"
};

const char* language_table_reject[] = {
	"Reject",
	"拒绝",
	"拒絕",
	"Rejeter",
	"Rechazar",
	"رفض",
	"拒否する",
	"Отклонить",
	"거부하다",
	"Rejeitar",
	"Rejeitar do Brasil",
	"Rifiutare",
	"Ablehnen",
	"अस्वीकृत करें",
	"Татгалзах",
	"ปฏิเสธ",
	"Відхилити",
	"Từ chối",
	"Tolak",
	"Tanggihan",
	"拒绝"
};

const char* language_table_confirm_transaction[] = {
	"Confirm Transaction",
	"确认交易",
	"確認交易",
	"Confirmer la transaction",
	"Confirmar transacción",
	"تأكيد المعاملة",
	"取引を確認",
	"Подтвердите транзакцию",
	"거래 확인",
	"Confirmar transação",
	"Confirmar transação",
	"Conferma Transazione",
	"Transaktion bestätigen",
	"लेन-देन की पुष्टि करें",
	"Бидний гүйлгээний баталгаа",
	"ยืนยันธุรกรรม",
	"Підтвердити транзакцію",
	"Xác nhận giao dịch",
	"Konfirmasi Transaksi",
	"Kumpirmahin ang Transaksyon",
	"লেনদেন নিশ্চিত করুন"
};

const char* language_table_sign_transaction[] = {
	"Do you want to sign this transaction?",
	"您要签署此交易吗？",
	"您是否要簽署此交易？",
	"Voulez-vous signer cette transaction ?",
	"¿Quieres firmar esta transacción?",
	"هل تريد توقيع هذه المعاملة؟",
	"この取引に署名しますか？",
	"Хотите подписать эту транзакцию?",
	"이 거래에 서명하시겠습니까?",
	"Deseja assinar esta transação?",
	"Deseja assinar esta transação?",
	"Vuoi firmare questa transazione?",
	"Möchten Sie diese Transaktion unterschreiben?",
	"क्या आप इस लेन-देन पर साइन करना चाहते हैं?",
	"Та энэхүү гүйлгээг гарын үсгээр баталгаажуулахыг хүсэж байна уу?",
	"คุณต้องการลงนามในธุรกรรมนี้หรือไม่?",
	"Чи хочеш підписати цю транзакцію?",
	"Bạn có muốn ký giao dịch này không?",
	"Apakah Anda ingin menandatangani transaksi ini?",
	"Gusto mo bang pirmahan ang transaksyon na ito?",
	"আপনি এই লেনদেনে সই করতে চান কি?"
};

const char* language_table_slide_to_sign[] = {
	"Slide to Sign",
	"滑动以签署",
	"滑動以簽署",
	"Faites glisser pour signer",
	"Desliza para firmar",
	"اسحب للتوقيع",
	"スライドして署名",
	"Проведите для подписи",
	"서명하려면 슬라이드하세요",
	"Deslize para assinar",
	"Deslize para assinar",
	"Scorri per firmare",
	"Zum Signieren schieben",
	"साइन करने के लिए स्लाइड करें",
	"Гарын үсэг зурахыг хүсвэл зураад явуулна уу",
	"เลื่อนเพื่อเซ็นชื่อ",
	"Проведіть для підписання",
	"Kéo để ký",
	"Geser untuk Menandatangani",
	"Mag-slide para pumirma",
	"সই করার জন্য স্লাইড করুন"
};

const char* language_table_processing[] = {
	"Processing …",
	"处理中 …",
	"處理中 …",
	"Traitement en cours …",
	"Procesando …",
	"معالجة …",
	"処理中 …",
	"Обработка …",
	"처리 중 …",
	"Processando …",
	"Processando …",
	"Elaborazione in corso …",
	"Verarbeitung …",
	"प्रसंस्करण …",
	"Боловсруулж байна …",
	"กำลังดำเนินการ …",
	"Обробка …",
	"Đang xử lý …",
	"Memproses …",
	"Paggawa …",
	"প্রক্রিয়াধীন …"
};

const char* language_table_transaction_successful[] = {
	"Transaction Successful",
	"交易成功",
	"交易成功",
	"Transaction réussie",
	"Transacción exitosa",
	"المعاملة ناجحة",
	"取引成功",
	"Сделка успешна",
	"거래 성공",
	"Transação bem-sucedida",
	"Transação bem-sucedida",
	"Transazione riuscita",
	"Transaktion erfolgreich",
	"लेन-देन सफल",
	"Амжилттай гүйлгээ",
	"ธุรกรรมสำเร็จ",
	"Транзакція успішна",
	"Giao dịch thành công",
	"Transaksi berhasil",
	"Matagumpay na transaksyon",
	"লেনদেন সফল"
};
const char* language_table_mul_language[] = {
	"English",
	"简体中文",
	"繁體中文",
	"Français",
	"Español",
	"العربية",
	"日本語",
	"Русский",
	"한국어",
	"Português",
	"Português do Brasil",
	"Italiano",
	"Deutsch",
	"हिन्दी",
	"Монгол",
	"ไทย",
	"Українська",
	"Tiếng Việt",
	"Bahasa Indonesia",
	"Tagalog",
	"বাংলা"
};

const char* language_table_add_finger[] = {
	"Add Finger",
	"添加指纹",
	"添加指紋",
	"Ajouter un doigt",
	"Agregar dedo",
	"إضافة إصبع",
	"指を追加",
	"Добавить палец"
};

const char* language_table_finger[] = {
    "Finger",
    "指纹",
    "指紋",
    "Empreinte digitale",
    "Huella digital",
    "بصمة",
    "指紋",
    "Отпечаток пальца"
};
const char* language_table_add_finger_prompt[] = {
	"Allow up to 3 fingerprints to be recorded simultaneously.",
	"允许同时记录最多3个指纹。",
	"允許同時記錄最多3個指紋。",
	"Permet d'enregistrer jusqu'à 3 empreintes digitales simultanément.",
	"Permite registrar hasta 3 huellas digitales simultáneamente.",
	"يسمح بتسجيل ما يصل إلى 3 بصمات في نفس الوقت.",
	"同時に最大3つの指紋を登録できます。",
	"Позволяет одновременно записывать до 3 отпечатков пальцев."
};
const char* language_table_unlock_device[] = {
    "Unlock Device",
    "解锁设备",
    "解鎖設備",
    "Déverrouiller l'appareil",
    "Desbloquear el dispositivo",
    "فتح الجهاز",
    "デバイスのロックを解除",
    "Разблокировать устройство"
};
const char* language_table_fingerprint[] = {
	"Fingerprint",
	"指纹",
	"指紋",
	"Empreinte digitale",
	"Huella digital",
	"بصمة",
	"指紋",
	"Отпечаток пальца"
};
const char* language_table_get_started[] = {
	"Get Started",
	"开始",
	"開始",
	"Commencer",
	"Comenzar",
	"ابدأ",
	"始める",
	"Начать"
};
const char* language_table_place_finger[] = {
	"Place Finger",
	"放置指纹",
	"放置指紋",
	"Placer le doigt",
	"Colocar el dedo",
	"وضع الإصبع",
	"指を置く",
	"Положите палец"
};
const char* language_table_put_finger_power_button[] = {
	"Put your finger on the power button and lift it afterwards, repeating this step.",
	"把手指放在电源按钮上，然后抬起，重复此步骤。",
	"将手指放在电源按钮上，然后抬起，重复此步骤。",
	"Mettez votre doigt sur le bouton d'alimentation et relevez-le ensuite, en répétant cette étape.",
	"Coloque su dedo en el botón de encendido y levántelo después, repitiendo este paso.",
	"ضع إصبعك على زر التشغيل ثم ارفعه لاحقًا، مكررًا هذه الخطوة.",
	"電源ボタンに指を置き、その後持ち上げてこのステップを繰り返します。",
	"Положите палец на кнопку питания, затем поднимите его, повторяя этот шаг."
};
const char* language_table_lift_and_touch_power_button[] = {
	"Lift and fine-tune the position, then touch power button again.",
	"抬起并微调位置，然后再次触摸电源按钮。",
	"抬起并微調位置，然後再次觸摸電源按鈕。",
	"Soulevez et ajustez la position, puis touchez à nouveau le bouton d'alimentation.",
	"Levante y ajuste la posición, luego toque el botón de encendido nuevamente.",
	"ارفع وقم بضبط الوضع، ثم اضغط على زر الطاقة مرة أخرى.",
	"持ち上げて位置を微調整し、もう一度電源ボタンに触れてください。",
	"Поднимите и отрегулируйте положение, затем коснитесь кнопки питания снова."
};
const char* language_table_fingerprint_added[] = {
	"Fingerprint Added",
	"指纹已添加",
	"指紋已添加",
	"Empreinte digitale ajoutée",
	"Huella digital añadida",
	"بصمة مضافة",
	"指紋が追加されました",
	"Отпечаток пальца добавлен"
};
const char* language_table_finger_1_added[] = {
	"Finger 1 has been added and can be",
	"手指1已添加，可以",
	"手指1已添加，可以",
	"Le doigt 1 a été ajouté et peut être",
	"El dedo 1 ha sido añadido y puede ser",
	"تمت إضافة الإصبع 1 ويمكن",
	"指1が追加され、次のことができます",
	"Палец 1 был добавлен и может быть"
};
const char* language_table_remove_fingerprints[] = {
	"Remove this fingerprints?",
	"删除这些指纹吗？",
	"刪除這些指紋嗎？",
	"Supprimer ces empreintes digitales ?",
	"¿Eliminar estas huellas digitales?",
	"حذف هذه البصمات؟",
	"この指紋を削除しますか？",
	"Удалить эти отпечатки пальцев?"
};
const char* language_table_confirm_remove_fingerprint[] = {
	"Are you sure you want to remove this fingerprint?",
	"您确定要删除这个指纹吗？",
	"您確定要刪除此指紋嗎？",
	"Êtes-vous sûr de vouloir supprimer cette empreinte digitale ?",
	"¿Está seguro de que desea eliminar esta huella digital?",
	"هل أنت متأكد أنك تريد إزالة هذه البصمة؟",
	"この指紋を本当に削除しますか？",
	"Вы уверены, что хотите удалить этот отпечаток пальца?"
};
const char* language_table_remove[] = {
	"Remove",
	"删除",
	"移除",
	"Supprimer",
	"Eliminar",
	"إزالة",
	"削除",
	"Удалить"
};
const char* language_table_alternative_pin_unlock[] = {
	"Alternative way to PIN unlocking! Enable fingerprint identity sensor and makes it easy for you to get into LIKKIM device.",
	"替代PIN解锁的方式！启用指纹身份传感器，让您更轻松地进入LIKKIM设备。",
	"替代PIN解鎖的方式！啟用指紋身份傳感器，讓您更輕鬆地進入LIKKIM設備。",
	"Méthode alternative pour déverrouiller le PIN ! Activez le capteur d'identité par empreinte digitale pour faciliter votre accès au dispositif LIKKIM.",
	"¡Método alternativo para desbloquear el PIN! Active el sensor de identidad de huellas digitales para facilitar su acceso al dispositivo LIKKIM.",
	"طريقة بديلة لفتح PIN! قم بتمكين مستشعر هوية بصمة الإصبع لجعل الدخول إلى جهاز LIKKIM أسهل.",
	"PINのロック解除の代替手段！指紋認証センサーを有効にして、LIKKIMデバイスに簡単にアクセスできます。",
	"Альтернативный способ разблокировки PIN! Включите сенсор отпечатков пальцев, чтобы упростить доступ к устройству LIKKIM."
};
const char* language_table_not_now[] = {
	"Not Now",
	"现在不",
	"現在不",
	"Pas maintenant",
	"No ahora",
	"ليس الآن",
	"今はいいえ",
	"Не сейчас"
};
const char* language_table_add_fingerprint[] = {
	"Add Fingerprint",
	"添加指纹",
	"添加指紋",
	"Ajouter une empreinte digitale",
	"Agregar huella digital",
	"إضافة بصمة",
	"指紋を追加",
	"Добавить отпечаток пальца"
};
const char* language_table_invalid_recovery_phrase[] = {
	"Invalid Recovery Phrase",
	"无效的恢复短语",
	"無效的恢復短語",
	"Phrase de récupération invalide",
	"Frase de recuperación no válida",
	"عبارة استرداد غير صالحة",
	"無効なリカバリーフレーズ",
	"Недействительная фраза восстановления"
};
const char* language_table_recovery_phrase_invalid[] = {
	"The recovery phrase you entered is invalid. Check your backup and try again.",
	"您输入的恢复短语无效。请检查您的备份并重试。",
	"您輸入的恢復短語無效。請檢查您的備份並重試。",
	"La phrase de récupération que vous avez saisie est invalide. Vérifiez votre sauvegarde et réessayez.",
	"La frase de recuperación que ingresaste no es válida. Verifica tu respaldo e inténtalo de nuevo.",
	"عبارة الاسترداد التي أدخلتها غير صالحة. تحقق من النسخة الاحتياطية الخاصة بك وحاول مرة أخرى.",
	"入力したリカバリーフレーズは無効です。バックアップを確認し、もう一度お試しください。",
	"Введенная вами фраза восстановления недействительна. Проверьте резервную копию и попробуйте снова."
};
const char* language_table_submitted[] = {
    "Submitted",
    "已经提交",
    "已经提交",
    "Soumis",
    "Enviado",
    "تم الإرسال",
    "提出しました",
    "Отправлено"
};

const char* language_table_incorrect_password[] = {
	"Incorrect password. Please try again.",
	"密码错误。请再尝试输入密码。",
	"密碼錯誤。請再試一次輸入密碼。",
	"Mot de passe incorrect. Veuillez réessayer.",
	"Contraseña incorrecta. Por favor, inténtalo de nuevo.",
	"كلمة المرور غير صحيحة. حاول مرة أخرى.",
	"パスワードが間違っています。再試行してください。",
	"Неправильный пароль. Попробуйте еще раз."
};
const char* language_table_incorrect_password_locked_1_min[] = {
    "Incorrect password. Locked for 1 minute, please try again after.",
	"密码错误。已锁定1分钟后可再次尝试。",
	"密碼錯誤。已鎖定1分鐘後可再次嘗試。",
    "Mot de passe incorrect. Verrouillé pendant 1 minute, veuillez réessayer après.",
    "Contraseña incorrecta. Bloqueado durante 1 minuto, por favor, inténtalo de nuevo después.",
    "كلمة المرور غير صحيحة. مقفلة لمدة 1 دقيقة، يرجى المحاولة مرة أخرى بعد.",
    "パスワードが間違っています。1分間ロックされているので、再試行してください。",
    "Неправильный пароль. Заблокировано на 1 минуту, попробуйте снова позже."
};
const char* language_table_incorrect_password_locked_5_min[] = {
    "Incorrect password. Locked for 5 minutes, please try again after.",
	"密码错误。已锁定5分钟后可再次尝试。",
	"密碼錯誤。已鎖定5分鐘後可再次嘗試。",
    "Mot de passe incorrect. Verrouillé pendant 5 minutes, veuillez réessayer après.",
    "Contraseña incorrecta. Bloqueado durante 5 minutos, por favor, inténtalo de nuevo después.",
    "كلمة المرور غير صحيحة. مقفلة لمدة 5 دقائق، يرجى المحاولة مرة أخرى بعد.",
    "パスワードが間違っています。5分間ロックされているので、再試行してください。",
    "Неправильный пароль. Заблокировано на 5 минут, попробуйте снова позже."
};
const char* language_table_incorrect_password_locked_1_hours[] = {
    "Incorrect password. Locked for 1 hour, please try again after.",
	"密码错误。已锁定1小时后可再次尝试。",
	"密碼錯誤。已鎖定1小時後可再次嘗試。",
    "Mot de passe incorrect. Verrouillé pendant 1 heure, veuillez réessayer après.",
    "Contraseña incorrecta. Bloqueado durante 1 hora, por favor, inténtalo de nuevo después.",
    "كلمة المرور غير صحيحة. مقفلة لمدة ساعة، يرجى المحاولة مرة أخرى بعد.",
    "パスワードが間違っています。1時間ロックされているので、再試行してください。",
    "Неправильный пароль. Заблокировано на 1 час, попробуйте снова позже."
};
const char* language_table_incorrect_password_locked_2_hours[] = {
    "Incorrect password. Locked for 2 hours, please try again after.",
	"密码错误。已锁定2小时后可再次尝试。",
	"密碼錯誤。已鎖定2小時後可再次嘗試。",
    "Mot de passe incorrect. Verrouillé pendant 2 heures, veuillez réessayer après.",
    "Contraseña incorrecta. Bloqueado durante 2 horas, por favor, inténtalo de nuevo después.",
    "كلمة المرور غير صحيحة. مقفلة لمدة ساعتين، يرجى المحاولة مرة أخرى بعد.",
    "パスワードが間違っています。2時間ロックされているので、再試行してください。",
    "Неправильный пароль. Заблокировано на 2 часа, попробуйте снова позже."
};
const char* language_table_incorrect_password_locked_4_hours[] = {
    "Incorrect password. Locked for 4 hours, please try again after.",
	"密码错误。已锁定4小时后可再次尝试。",
	"密碼錯誤。已鎖定4小時後可再次嘗試。",
    "Mot de passe incorrect. Verrouillé pendant 4 heures, veuillez réessayer après.",
    "Contraseña incorrecta. Bloqueado durante 4 horas, por favor, inténtalo de nuevo después.",
    "كلمة المرور غير صحيحة. مقفلة لمدة 4 ساعات، يرجى المحاولة مرة أخرى بعد.",
    "パスワードが間違っています。4時間ロックされているので、再試行してください。",
    "Неправильный пароль. Заблокировано на 4 часа, попробуйте снова позже."
};
const char* language_table_incorrect_password_locked_8_hours[] = {
    "Incorrect password. Locked for 8 hours, please try again after.",
	"密码错误。已锁定8小时后可再次尝试。",
	"密碼錯誤。已鎖定8小時後可再次嘗試。",
    "Mot de passe incorrect. Verrouillé pendant 8 heures, veuillez réessayer après.",
    "Contraseña incorrecta. Bloqueado durante 8 horas, por favor, inténtalo de nuevo después.",
    "كلمة المرور غير صحيحة. مقفلة لمدة 8 ساعات، يرجى المحاولة مرة أخرى بعد.",
    "パスワードが間違っています。8時間ロックされているので、再試行してください。",
    "Неправильный пароль. Заблокировано на 8 часов, попробуйте снова позже."
};
const char* language_table_incorrect_password_2_attempts[] = {
    "Incorrect password. You have 2 attempts left. Exceeding the limit.",
	"密码错误。您还有2次输入机会，超出次数将抹除所有数据。",
	"密碼錯誤。您還有2次輸入機會，超出次數將抹除所有數據。",
    "Mot de passe incorrect. Il vous reste 2 tentatives. Dépassant la limite.",
    "Contraseña incorrecta. Te quedan 2 intentos. Excediendo el límite.",
    "كلمة المرور غير صحيحة. لديك 2 محاولات متبقية. تجاوز الحد.",
    "パスワードが間違っています。あと2回試せます。制限を超えています。",
    "Неправильный пароль. У вас осталось 2 попытки. Превышая лимит."
};
const char* language_table_incorrect_password_1_attempt[] = {
    "Incorrect password. You have 1 attempt left. Exceeding the limit.",
	"密码错误。您还有1次输入机会，超出次数将抹除所有数据。",
	"密碼錯誤。您還有1次輸入機會，超出次數將抹除所有數據。",
    "Mot de passe incorrect. Il vous reste 1 tentative. Dépassant la limite.",
    "Contraseña incorrecta. Te queda 1 intento. Excediendo el límite.",
    "كلمة المرور غير صحيحة. لديك محاولة واحدة متبقية. تجاوز الحد.",
    "パスワードが間違っています。あと1回試せます。制限を超えています。",
    "Неправильный пароль. У вас осталась 1 попытка. Превышая лимит."
};

const char* language_table_nft_gallery[] = {
	"NFT Gallery",
	"NFT 畫廊",
	"NFT 畫廊",
	"Galerie NFT",
	"Galería de NFT",
	"معرض NFT",
	"ギャラリーNFT",
	"Галерея NFT",
	"NFT 갤러리",
	"Galeria de NFT",
	"Galeria de NFT",
	"Galleria NFT",
	"NFT-Galerie",
	"गैलरी NFT",
	"Галерея NFT",
	"แกลเลอรี NFT",
	"Галерея NFT",
	"NFT Gallery",
	"Galeri NFT",
	"NFT Gallery",
	"NFT গ্যালারি"
};

const char* language_table_nft_gallery_infomation[] = {
	"Open the LIKKIM app, locate the NFT linked to this hardware wallet, and press the 'Add to Collection' button.",
	"打开LIKKIM应用，找到与此硬件钱包链接的NFT，点击'添加到收藏'按钮。",
	"打開LIKKIM應用，找到與此硬件錢包鏈接的NFT，點擊'添加到收藏'按鈕。",
	"ouvrez l'application LIKKIM, localisez le NFT lié à ce portefeuille matériel et appuyez sur le bouton 'Ajouter à la collection'.",
	"abre la aplicación LIKKIM, localiza el NFT vinculado a esta billetera de hardware y presiona el botón 'Agregar a la colección'.",
	"افتح تطبيق LIKKIM ، وابحث عن NFT المرتبط بمحفظة الأجهزة هذه ، واضغط على زر 'إضافة إلى المجموعة'.",
	"LIKKIMアプリを開き、このハードウェアウォレットにリンクされたNFTを探し、「コレクションに追加」ボタンを押してください。",
	"откройте приложение LIKKIM, найдите NFT, связанный с этим аппаратным кошельком, и нажмите кнопку 'Добавить в коллекцию'.",
	"LIKKIM 앱을 열고 이 하드웨어 지갑에 연결된 NFT를 찾아 '컬렉션에 추가' 버튼을 누르세요.",
	"abra o aplicativo LIKKIM, localize o NFT vinculado a esta carteira de hardware e pressione o botão 'Adicionar à Coleção'.",
	"abra o aplicativo LIKKIM, localize o NFT vinculado a esta carteira de hardware e pressione o botão 'Adicionar à Coleção'.",
	"apri l'app LIKKIM, trova il NFT collegato a questo portafoglio hardware e premi il pulsante 'Aggiungi alla collezione'.",
	"öffnen Sie die LIKKIM-App, suchen Sie das mit dieser Hardware-Wallet verknüpfte NFT und drücken Sie die Schaltfläche 'Zur Sammlung hinzufügen'.",
	"खुला LIKKIM ऐप, इस हार्डवेयर वॉलेट से जुड़ा हुआ NFT ढूंढें, और 'संग्रह में जोड़ें' बटन दबाएं।",
	"откройте приложение LIKKIM, найдите NFT, связанный с этим аппаратным кошельком, и нажмите кнопку 'Добавить в коллекцию'.",
	"เปิดแอป LIKKIM, ค้นหา NFT ที่เชื่อมโยงกับกระเป๋าเงินฮาร์ดแวร์นี้ และกดปุ่ม 'เพิ่มในคอลเลกชัน'。",
	"відкрийте додаток LIKKIM, знайдіть NFT, прив'язаний до цього апаратного гаманця, і натисніть кнопку 'Додати до колекції'.",
	"Mở ứng dụng LIKKIM, tìm NFT liên kết với ví phần cứng này và nhấn nút 'Thêm vào Bộ sưu tập'.",
	"buka aplikasi LIKKIM, temukan NFT yang terhubung dengan dompet perangkat keras ini, dan tekan tombol 'Tambahkan ke Koleksi'.",
	"bukas ang LIKKIM app, hanapin ang NFT na naka-link sa hardware wallet na ito, at i-press ang 'Add to Collection' na button.",
	"খুলুন LIKKIM অ্যাপ, এই হার্ডওয়্যার ওয়ালেটের সাথে সংযুক্ত NFT খুঁজুন এবং 'কোলেকশনে যুক্ত করুন' বোতামটি টিপুন।"
};

void set_language_string(lv_obj_t *label, uint8_t font_size, const char** str_table)
{
	language_type_t type = gui_data_get_language_type();

	if (font_size == 40)
		lv_obj_set_style_text_font(label, &font_40, 0);
	else if (font_size == 32)
		lv_obj_set_style_text_font(label, &font_32, 0);
	else if (font_size == 24)
		lv_obj_set_style_text_font(label, &font_24, 0);

	lv_label_set_text(label, str_table[type]);
}


